export const IPC = {
  dialogOpenDirectory: 'dialog:openDirectory',
  dialogOpenSaveProject: 'dialog:openSaveProject',
  fsListDir: 'fs:listDir',
  fsReadFile: 'fs:readFile',
  fsWriteFile: 'fs:writeFile',
  fsCreateFile: 'fs:createFile',
  fsCreateDir: 'fs:createDir',
  fsRename: 'fs:rename',
  fsDelete: 'fs:delete',
  fsExists: 'fs:exists',
  projectGetRecent: 'project:getRecent',
  projectAddRecent: 'project:addRecent',
  projectDetect: 'project:detect',
  projectCreate: 'project:create',
  gitStatus: 'git:status',
  gitStage: 'git:stage',
  gitUnstage: 'git:unstage',
  gitCommit: 'git:commit',
  terminalCreate: 'terminal:create',
  terminalWrite: 'terminal:write',
  terminalResize: 'terminal:resize',
  terminalKill: 'terminal:kill',
  terminalData: 'terminal:data',
  terminalExit: 'terminal:exit',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  appGetVersion: 'app:getVersion',
  aiGetPublicSettings: 'ai:getPublicSettings',
  aiSetSettings: 'ai:setSettings',
  aiSetApiKey: 'ai:setApiKey',
  aiClearApiKey: 'ai:clearApiKey',
  aiTestConnection: 'ai:testConnection',
  aiChatStart: 'ai:chatStart',
  aiChatAbort: 'ai:chatAbort',
  aiChatChunk: 'ai:chatChunk'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
