/** Worldwide tourism destinations for Canaan Travel Hub (enquiry-first unless published). */

import { DEFAULT_PLACES } from "./default-places.mjs";

export const REGION_IMAGES = {
  india: "/images/marketing/kodai-banner.jpg",
  asia: "/images/kodai/pine-forest.webp",
  europe: "/images/kodai/bryant.webp",
  middleEast: "/images/kodai/coakers-walk.webp",
  americas: "/images/kodai/mannavanur.webp",
  africa: "/images/kodai/berijam.webp",
  oceania: "/images/kodai/kodai-lake.webp",
  islands: "/images/kodai/kodai-lake.webp",
};

/** @typedef {{ slug: string; nameEn: string; country: string; continent: string; region: string; taglineEn: string; bodyEn: string; image?: string; status?: string; featured?: boolean; priceFrom?: number; sortOrder?: number; places?: { slug: string; nameEn: string; summaryEn: string }[] }} WorldDestination */

/** @type {WorldDestination[]} */
export const WORLD_DESTINATIONS = [
  // India — published / enquiry
  {
    slug: "kodaikanal",
    nameEn: "Kodaikanal",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Princess of the Hills — our flagship destination",
    bodyEn:
      "Misty pine forests, quiet lakes, and verified Kodaikanal packages. Canaan also supports flights, hotels, and visas worldwide.",
    status: "published",
    featured: true,
    priceFrom: 1799,
    sortOrder: 1,
    places: [
      { slug: "kodai-lake", nameEn: "Kodaikanal Lake", summaryEn: "Boating and lakeside walks in the hill town centre." },
      { slug: "coakers-walk", nameEn: "Coaker's Walk", summaryEn: "A classic ridge walk with valley views on clear mornings." },
      { slug: "pillar-rocks", nameEn: "Pillar Rocks", summaryEn: "Iconic vertical rock pillars above misty valleys." },
      { slug: "berijam-lake", nameEn: "Berijam Lake", summaryEn: "Forest-fringed reservoir — permit and timing rules apply." },
    ],
  },
  {
    slug: "darjeeling",
    nameEn: "Darjeeling",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Tea hills, Tiger Hill, and NJP circuits",
    bodyEn:
      "Verified 3 Night / 4 Day Darjeeling group packages from NJP — tea estates, town sightseeing, and Mirik return routes.",
    status: "published",
    featured: true,
    priceFrom: 6550,
    sortOrder: 2,
    places: [
      { slug: "tiger-hill", nameEn: "Tiger Hill", summaryEn: "Early sunrise views toward Kanchenjunga on clear mornings." },
      { slug: "happy-valley-tea", nameEn: "Happy Valley Tea Estate", summaryEn: "Working tea estate visits and tastings when open." },
      { slug: "mirik-lake", nameEn: "Mirik Lake", summaryEn: "Pine air and a softer pace on common return-day routes." },
    ],
  },
  {
    slug: "goa",
    nameEn: "Goa",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Coastal calm, heritage churches, and custom beach plans",
    bodyEn:
      "Goa is enquiry-first on Canaan — custom beach tours, water sports, and sightseeing without invented package prices.",
    status: "coming_soon",
    featured: true,
    sortOrder: 3,
    places: [
      { slug: "old-goa", nameEn: "Old Goa churches", summaryEn: "UNESCO-listed heritage including Basilica of Bom Jesus." },
      { slug: "dudhsagar", nameEn: "Dudhsagar Falls", summaryEn: "Seasonal waterfall day trips — access depends on weather." },
      { slug: "palolem", nameEn: "Palolem Beach", summaryEn: "South Goa's crescent sand — popular for calm holidays." },
    ],
  },
  {
    slug: "kerala",
    nameEn: "Kerala",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Backwaters, houseboats, and Malabar coast rhythm",
    bodyEn: "Custom Kerala itineraries — Alleppey backwaters, Munnar hills, and Kochi heritage through Canaan enquiry planning.",
    sortOrder: 10,
    places: [
      { slug: "alleppey", nameEn: "Alleppey backwaters", summaryEn: "Houseboat routes and village canals in Kuttanad." },
      { slug: "munnar", nameEn: "Munnar", summaryEn: "Tea hills and cooler air above the plains." },
    ],
  },
  {
    slug: "rajasthan",
    nameEn: "Rajasthan",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Forts, deserts, and palace cities",
    bodyEn: "Jaipur, Udaipur, Jaisalmer, and desert camps — custom Rajasthan circuits arranged on enquiry.",
    sortOrder: 11,
    places: [
      { slug: "jaipur", nameEn: "Jaipur", summaryEn: "Pink City forts, bazaars, and Hawa Mahal." },
      { slug: "udaipur", nameEn: "Udaipur", summaryEn: "Lake Pichola, City Palace, and romantic old-town walks." },
    ],
  },
  {
    slug: "manali",
    nameEn: "Manali",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Himalayan gateway and Solang adventures",
    bodyEn: "Hill stays, Rohtang-season planning, and family-friendly Himachal routes — enquire for dates and road conditions.",
    sortOrder: 12,
  },
  {
    slug: "leh-ladakh",
    nameEn: "Leh & Ladakh",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "High desert passes and monastery silences",
    bodyEn: "Altitude-aware Ladakh planning — Nubra, Pangong, and acclimatisation built into custom itineraries.",
    sortOrder: 13,
  },
  {
    slug: "andaman",
    nameEn: "Andaman Islands",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Turquoise bays and coral-fringed calm",
    bodyEn: "Port Blair, Havelock, and Neil Island combinations — ferry timing and season matter; enquire early.",
    sortOrder: 14,
  },
  {
    slug: "agra-taj-mahal",
    nameEn: "Agra & Taj Mahal",
    country: "India",
    continent: "Asia",
    region: "india",
    taglineEn: "Mughal heritage and the marble monument",
    bodyEn: "Sunrise Taj visits, Agra Fort, and Golden Triangle add-ons — custom city and rail plans.",
    sortOrder: 15,
  },
  // Asia
  {
    slug: "bali",
    nameEn: "Bali",
    country: "Indonesia",
    continent: "Asia",
    region: "asia",
    taglineEn: "Temples, rice terraces, and warm island evenings",
    bodyEn: "Ubud culture, Seminyak stays, and volcano viewpoints — Canaan arranges Bali through worldwide tourism support.",
    featured: true,
    sortOrder: 20,
    places: [
      { slug: "ubud", nameEn: "Ubud", summaryEn: "Rice terraces, crafts, and calmer inland pacing." },
      { slug: "tanah-lot", nameEn: "Tanah Lot", summaryEn: "Sea temple sunsets — tide and crowd timing matter." },
    ],
  },
  {
    slug: "dubai",
    nameEn: "Dubai",
    country: "UAE",
    continent: "Middle East",
    region: "middleEast",
    taglineEn: "Skyline luxury and desert horizons",
    bodyEn: "City stays, desert safaris, and family attractions — flights, hotels, and transfers on enquiry.",
    featured: true,
    sortOrder: 21,
  },
  {
    slug: "singapore",
    nameEn: "Singapore",
    country: "Singapore",
    continent: "Asia",
    region: "asia",
    taglineEn: "Garden city precision and food-hall evenings",
    bodyEn: "Short-stay city breaks, Sentosa, and transit-friendly stopovers — ideal for families and first Asia trips.",
    sortOrder: 22,
  },
  {
    slug: "bangkok",
    nameEn: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    region: "asia",
    taglineEn: "Temples, markets, and river-city energy",
    bodyEn: "Grand Palace area, Chao Phraya evenings, and gateway hops to Phuket or Chiang Mai.",
    sortOrder: 23,
  },
  {
    slug: "phuket",
    nameEn: "Phuket",
    country: "Thailand",
    continent: "Asia",
    region: "asia",
    taglineEn: "Andaman beaches and island-hopping bases",
    bodyEn: "Beach zones from Patong to Kata — custom resort and transfer planning without fixed Canaan packages.",
    sortOrder: 24,
  },
  {
    slug: "tokyo",
    nameEn: "Tokyo",
    country: "Japan",
    continent: "Asia",
    region: "asia",
    taglineEn: "Neon districts and precise transit calm",
    bodyEn: "Shibuya, Asakusa, and day trips toward Hakone or Nikko — visa and rail advice on enquiry.",
    sortOrder: 25,
  },
  {
    slug: "kyoto",
    nameEn: "Kyoto",
    country: "Japan",
    continent: "Asia",
    region: "asia",
    taglineEn: "Shrines, bamboo groves, and seasonal restraint",
    bodyEn: "Fushimi Inari, Arashiyama, and autumn/spring planning — slower pacing suits this city best.",
    sortOrder: 26,
  },
  {
    slug: "seoul",
    nameEn: "Seoul",
    country: "South Korea",
    continent: "Asia",
    region: "asia",
    taglineEn: "Palaces, cafés, and DMZ day options",
    bodyEn: "Gyeongbokgung, Hongdae evenings, and winter or cherry-blossom seasons — custom city breaks.",
    sortOrder: 27,
  },
  {
    slug: "hong-kong",
    nameEn: "Hong Kong",
    country: "China",
    continent: "Asia",
    region: "asia",
    taglineEn: "Harbour skylines and dim-sum mornings",
    bodyEn: "Victoria Peak, ferries, and short-stay stopovers en route to wider Asia.",
    sortOrder: 28,
  },
  {
    slug: "vietnam",
    nameEn: "Vietnam",
    country: "Vietnam",
    continent: "Asia",
    region: "asia",
    taglineEn: "Ha Long bays, Hoi An lanes, and pho trails",
    bodyEn: "North-to-south or focused central Vietnam — trains, flights, and guided days on enquiry.",
    sortOrder: 29,
  },
  {
    slug: "cambodia",
    nameEn: "Cambodia",
    country: "Cambodia",
    continent: "Asia",
    region: "asia",
    taglineEn: "Angkor dawn and Mekong calm",
    bodyEn: "Angkor Wat timing, Siem Reap stays, and respectful temple etiquette in custom plans.",
    sortOrder: 30,
  },
  {
    slug: "sri-lanka",
    nameEn: "Sri Lanka",
    country: "Sri Lanka",
    continent: "Asia",
    region: "asia",
    taglineEn: "Tea country, coast, and cultural triangle",
    bodyEn: "Sigiriya, Ella trains, and south-coast beaches — round-island pacing tailored to your days.",
    sortOrder: 31,
  },
  {
    slug: "maldives",
    nameEn: "Maldives",
    country: "Maldives",
    continent: "Asia",
    region: "islands",
    taglineEn: "Overwater calm and turquoise mornings",
    bodyEn: "Resort selection, seaplane transfers, and honeymoon-ready arrangements — no invented Canaan package prices.",
    featured: true,
    sortOrder: 32,
    image: "/images/kodai/kodai-lake.webp",
  },
  {
    slug: "nepal",
    nameEn: "Nepal",
    country: "Nepal",
    continent: "Asia",
    region: "asia",
    taglineEn: "Kathmandu heritage and Himalayan gateways",
    bodyEn: "Kathmandu Valley, Pokhara lakes, and trek planning support — altitude and season advice included.",
    sortOrder: 33,
  },
  {
    slug: "bhutan",
    nameEn: "Bhutan",
    country: "Bhutan",
    continent: "Asia",
    region: "asia",
    taglineEn: "Tiger's Nest trails and measured tourism",
    bodyEn: "Permit-aware Bhutan itineraries — Paro, Thimphu, and festival timing on custom enquiry.",
    sortOrder: 34,
  },
  {
    slug: "malaysia",
    nameEn: "Malaysia",
    country: "Malaysia",
    continent: "Asia",
    region: "asia",
    taglineEn: "Kuala Lumpur towers and Langkawi islands",
    bodyEn: "City breaks, Penang food trails, and island hops — ASEAN-friendly family routing.",
    sortOrder: 35,
  },
  // Middle East & Africa
  {
    slug: "qatar",
    nameEn: "Qatar",
    country: "Qatar",
    continent: "Middle East",
    region: "middleEast",
    taglineEn: "Doha stopovers and desert art districts",
    bodyEn: "Short luxury stopovers and museum districts — ideal en route to Europe or Asia.",
    sortOrder: 40,
  },
  {
    slug: "oman",
    nameEn: "Oman",
    country: "Oman",
    continent: "Middle East",
    region: "middleEast",
    taglineEn: "Wadis, forts, and Arabian Sea coast",
    bodyEn: "Muscat base, Nizwa day trips, and desert camps — custom driving routes on enquiry.",
    sortOrder: 41,
  },
  {
    slug: "jordan",
    nameEn: "Jordan",
    country: "Jordan",
    continent: "Middle East",
    region: "middleEast",
    taglineEn: "Petra passages and Wadi Rum stars",
    bodyEn: "Petra two-day pacing, Dead Sea floats, and Bedouin camp nights — heat and walking plans matter.",
    sortOrder: 42,
  },
  {
    slug: "turkey",
    nameEn: "Turkey",
    country: "Turkey",
    continent: "Europe",
    region: "europe",
    taglineEn: "Istanbul layers and Cappadocia skies",
    bodyEn: "Bosphorus mornings, balloon-season Cappadocia, and coastal Ephesus add-ons.",
    sortOrder: 43,
  },
  {
    slug: "egypt",
    nameEn: "Egypt",
    country: "Egypt",
    continent: "Africa",
    region: "africa",
    taglineEn: "Pyramids, Nile cruises, and Red Sea reefs",
    bodyEn: "Cairo–Luxor–Aswan sequencing and dive extensions — guided safety and heat-aware pacing.",
    sortOrder: 50,
  },
  {
    slug: "morocco",
    nameEn: "Morocco",
    country: "Morocco",
    continent: "Africa",
    region: "africa",
    taglineEn: "Marrakech souks and Sahara edges",
    bodyEn: "Medina walks, Atlas day trips, and desert camps — custom routing from Casablanca or Marrakech.",
    sortOrder: 51,
  },
  {
    slug: "kenya-safari",
    nameEn: "Kenya Safari",
    country: "Kenya",
    continent: "Africa",
    region: "africa",
    taglineEn: "Maasai Mara horizons and migration seasons",
    bodyEn: "Park selection, lodge tiers, and migration-window advice — wildlife seasons drive the itinerary.",
    sortOrder: 52,
  },
  {
    slug: "cape-town",
    nameEn: "Cape Town",
    country: "South Africa",
    continent: "Africa",
    region: "africa",
    taglineEn: "Table Mountain and Cape Peninsula drives",
    bodyEn: "City base, Cape Point, and Winelands day loops — custom self-drive or guided options.",
    sortOrder: 53,
  },
  // Europe
  {
    slug: "paris",
    nameEn: "Paris",
    country: "France",
    continent: "Europe",
    region: "europe",
    taglineEn: "Museum mornings and Seine evenings",
    bodyEn: "Landmark pacing, rail day trips, and visa-aware Europe entry planning.",
    featured: true,
    sortOrder: 60,
  },
  {
    slug: "london",
    nameEn: "London",
    country: "United Kingdom",
    continent: "Europe",
    region: "europe",
    taglineEn: "Royal parks, theatre nights, and Thames walks",
    bodyEn: "Museum clusters, Oyster transit, and UK side trips — custom city breaks on enquiry.",
    sortOrder: 61,
  },
  {
    slug: "rome",
    nameEn: "Rome",
    country: "Italy",
    continent: "Europe",
    region: "europe",
    taglineEn: "Ancient forums and trattoria evenings",
    bodyEn: "Colosseum timing, Vatican days, and Tuscany add-ons — walk-heavy pacing planned calmly.",
    sortOrder: 62,
  },
  {
    slug: "barcelona",
    nameEn: "Barcelona",
    country: "Spain",
    continent: "Europe",
    region: "europe",
    taglineEn: "Gaudí curves and Mediterranean bars",
    bodyEn: "Sagrada Família slots, Gothic Quarter walks, and Costa day trips.",
    sortOrder: 63,
  },
  {
    slug: "switzerland",
    nameEn: "Switzerland",
    country: "Switzerland",
    continent: "Europe",
    region: "europe",
    taglineEn: "Alpine precision and scenic rail journeys",
    bodyEn: "Interlaken, Lucerne, and rail pass advice — high-season lodging books early.",
    featured: true,
    sortOrder: 64,
  },
  {
    slug: "greece",
    nameEn: "Greece",
    country: "Greece",
    continent: "Europe",
    region: "europe",
    taglineEn: "Athens history and Cyclades ferries",
    bodyEn: "Acropolis mornings, Santorini sunsets, and island-hopping ferries — season and wind matter.",
    sortOrder: 65,
  },
  {
    slug: "iceland",
    nameEn: "Iceland",
    country: "Iceland",
    continent: "Europe",
    region: "europe",
    taglineEn: "Waterfalls, glaciers, and midnight sun",
    bodyEn: "Ring Road pacing, winter aurora realism, and 4x4 advice — weather drives daily plans.",
    sortOrder: 66,
  },
  {
    slug: "norway",
    nameEn: "Norway",
    country: "Norway",
    continent: "Europe",
    region: "europe",
    taglineEn: "Fjord ferries and Arctic summer light",
    bodyEn: "Bergen loops, Geiranger seasonality, and northern-light windows — custom Nordic routing.",
    sortOrder: 67,
  },
  {
    slug: "amsterdam",
    nameEn: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    region: "europe",
    taglineEn: "Canal rings and museum afternoons",
    bodyEn: "Rijksmuseum, Anne Frank House timing, and Benelux day trips — bike-friendly city breaks.",
    sortOrder: 68,
  },
  // Americas
  {
    slug: "new-york",
    nameEn: "New York",
    country: "USA",
    continent: "Americas",
    region: "americas",
    taglineEn: "Skyline walks and borough food trails",
    bodyEn: "Manhattan pacing, Broadway nights, and visa/interview timing support on enquiry.",
    featured: true,
    sortOrder: 70,
  },
  {
    slug: "los-angeles",
    nameEn: "Los Angeles",
    country: "USA",
    continent: "Americas",
    region: "americas",
    taglineEn: "Coast highways and studio-city sprawl",
    bodyEn: "Car-first planning, Santa Monica sunsets, and national-park side trips.",
    sortOrder: 71,
  },
  {
    slug: "las-vegas",
    nameEn: "Las Vegas",
    country: "USA",
    continent: "Americas",
    region: "americas",
    taglineEn: "Desert entertainment and Grand Canyon hops",
    bodyEn: "Short stays, show tickets, and helicopter or road day trips — heat and hydration matter.",
    sortOrder: 72,
  },
  {
    slug: "canada",
    nameEn: "Canada",
    country: "Canada",
    continent: "Americas",
    region: "americas",
    taglineEn: "Rockies rails and lake-country calm",
    bodyEn: "Banff/Jasper summer windows, Toronto–Niagara loops, and visa-aware planning.",
    sortOrder: 73,
  },
  {
    slug: "mexico",
    nameEn: "Mexico",
    country: "Mexico",
    continent: "Americas",
    region: "americas",
    taglineEn: "Riviera beaches and Mayan heritage",
    bodyEn: "Cancún bases, Tulum pacing, and Chichen Itza day trips — resort and culture combinations.",
    sortOrder: 74,
  },
  {
    slug: "peru",
    nameEn: "Peru",
    country: "Peru",
    continent: "Americas",
    region: "americas",
    taglineEn: "Machu Picchu trails and Lima food",
    bodyEn: "Acclimatisation in Cusco, permit-aware Inca routes, and Amazon extensions.",
    sortOrder: 75,
  },
  // Oceania
  {
    slug: "sydney",
    nameEn: "Sydney",
    country: "Australia",
    continent: "Oceania",
    region: "oceania",
    taglineEn: "Harbour icons and coastal walks",
    bodyEn: "Opera House angles, Bondi to Coogee, and Blue Mountains day options.",
    sortOrder: 80,
  },
  {
    slug: "new-zealand",
    nameEn: "New Zealand",
    country: "New Zealand",
    continent: "Oceania",
    region: "oceania",
    taglineEn: "South Island fjords and North Island geysers",
    bodyEn: "Self-drive South Island loops or focused North Island family routes — season and driving times matter.",
    sortOrder: 81,
  },
];

export function blogTemplates(dest) {
  const name = dest.nameEn;
  const country = dest.country;
  return [
    {
      slug: `${dest.slug}-travel-guide`,
      titleEn: `${name} travel guide for first-time visitors`,
      excerptEn: `How to pace ${name}, ${country} without rushing the highlights — practical planning notes from Canaan Travel Hub.`,
      tagsEn: [name, "Guides", "First visit"],
      readMinutes: 7,
      paragraphs: [
        `${name} rewards unhurried planning. Start with how many nights you truly have — not every highlight fits a short break.`,
        `Most travellers combine ${name} with wider ${country} routing or a focused city/resort base. Canaan builds custom plans on enquiry rather than fake live inventory.`,
        `Book flights and visas early for international trips. Shoulder seasons often balance weather, crowds, and cost better than peak holidays alone.`,
        `Share traveller ages, mobility needs, and must-do sights when you enquire — pacing changes everything for families and seniors.`,
        `Canaan supports published India packages where verified, and worldwide tourism assistance everywhere else — flights, hotels, visas, and itinerary design.`,
        `Use the blog filters on Canaan to read more ${name}-focused guides, then send dates and group size when you are ready to plan.`,
      ],
    },
    {
      slug: `best-time-to-visit-${dest.slug}`,
      titleEn: `Best time to visit ${name}`,
      excerptEn: `Season-by-season notes for ${name} — weather windows, crowds, and when to stay flexible.`,
      tagsEn: [name, "Seasons"],
      readMinutes: 5,
      paragraphs: [
        `The best time for ${name} depends on what you prioritise — dry weather, lower crowds, festivals, or specific activities like beaches or snow.`,
        `Peak tourist weeks raise prices and require earlier hotel and transfer booking. Shoulder weeks often feel calmer with acceptable weather.`,
        `Monsoon or winter extremes can still be beautiful with the right clothing and flexible sightseeing — forced outdoor days are the mistake to avoid.`,
        `If you are connecting ${name} with other ${country} stops, align seasons across the whole route, not one city alone.`,
        `Ask Canaan about your exact month before paying large advances — local conditions change year to year.`,
        `Build one buffer day for weather or transport delays on international holidays.`,
      ],
    },
    {
      slug: `how-to-reach-${dest.slug}`,
      titleEn: `How to reach ${name}`,
      excerptEn: `Airports, rail, and transfer tips for arriving in ${name} with less stress.`,
      tagsEn: [name, "Travel tips"],
      readMinutes: 5,
      paragraphs: [
        `International trips to ${name}, ${country} usually start with the best-fitting airport or rail hub for your origin city — Canaan advises on routing when you enquire.`,
        `Pre-booked airport transfers reduce arrival friction, especially after long flights or when travelling with elders and children.`,
        `Local transport varies: metro cities favour trains and rideshare; resort destinations may need private transfers between zones.`,
        `Keep passport, visa, and hotel confirmation offline on your phone. Immigration queues peak at holiday weekends.`,
        `If ${name} is part of a multi-country trip, sequence visas and baggage allowances before locking internal flights.`,
        `Tell Canaan your arrival time and terminal so pickup and first-night hotel timing stay realistic.`,
      ],
    },
    {
      slug: `${dest.slug}-top-sights`,
      titleEn: `Top sights in ${name}`,
      excerptEn: `A calm shortlist of what ${name} is known for — without treating the city like a checklist marathon.`,
      tagsEn: [name, "Sightseeing"],
      readMinutes: 6,
      paragraphs: [
        `${name} has signature sights that define most first visits. Choose two or three anchors per day instead of stacking distant points.`,
        ...(dest.places?.slice(0, 3).map(
          (p) =>
            `${p.nameEn}: ${p.summaryEn} Allow realistic time and local opening rules.`,
        ) ?? [
          `Heritage districts, viewpoints, and food markets usually anchor a good first ${name} day.`,
          `Museums and indoor sites help on rain or extreme heat days.`,
          `Evenings are for neighbourhoods, riverfronts, or beaches — not always more ticketed attractions.`,
        ]),
        `Photography and dress codes matter at religious or heritage sites — read signs and follow guide advice.`,
        `Canaan can sequence sights around your stay location to reduce backtracking.`,
      ],
    },
    {
      slug: `plan-${dest.slug}-with-canaan`,
      titleEn: `Plan ${name} with Canaan Travel Hub`,
      excerptEn: `What to send when you enquire for ${name} — dates, travellers, budget band, and must-dos.`,
      tagsEn: [name, "Planning"],
      readMinutes: 4,
      paragraphs: [
        `Share travel dates, origin city, group size, and whether ${name} is the only stop or part of a longer ${country} route.`,
        `Mention published Canaan packages only where they exist — otherwise expect a custom quote, not invented pricing.`,
        `List must-dos (beaches, temples, shopping, adventure) and absolute no-gos (long drives, nightlife, extreme sport).`,
        `Flights, hotels, visas, and travel insurance can be coordinated as digital tourism support alongside ground planning.`,
        `Response is human planning: clear next steps, not fake instant booking for complex international routes.`,
        `Use /enquire or WhatsApp with this context for the fastest useful reply about ${name}.`,
      ],
    },
  ];
}

/** Merge destination places with default place catalogue. */
export function placesForDestination(dest) {
  const listed = dest.places ?? [];
  const defaults = DEFAULT_PLACES[dest.slug] ?? [];
  const bySlug = new Map();
  for (const place of [...listed, ...defaults]) {
    if (!bySlug.has(place.slug)) bySlug.set(place.slug, place);
  }
  return [...bySlug.values()];
}

/** One dedicated blog for each tourist place. */
export function placeBlogTemplate(dest, place) {
  const destName = dest.nameEn;
  const placeName = place.nameEn;
  return {
    slug: `${dest.slug}-${place.slug}-guide`,
    titleEn: `${placeName}: visitor guide (${destName})`,
    excerptEn: `${place.summaryEn} Practical tips for visiting ${placeName} in ${destName}, ${dest.country}.`,
    tagsEn: [destName, placeName, "Sightseeing"],
    readMinutes: 5,
    paragraphs: [
      `${placeName} is one of the signature stops travellers look for in ${destName}, ${dest.country}. ${place.summaryEn}`,
      `Treat ${placeName} as a focused half-day or full-day anchor — not one of ten rushed ticks. Pair it with nearby rest, food, and transfer time.`,
      `Opening hours, tickets, dress codes, and weather can change. Confirm locally on the day and keep one flexible backup activity.`,
      `Families and elders should ask about walking distance, steps, and shade before locking the visit into a tight schedule.`,
      `Canaan Travel Hub can sequence ${placeName} into a custom ${destName} itinerary with flights, hotels, and visas where needed — enquire with your dates.`,
      `Published package prices apply only where Canaan lists them (for example select India circuits). Worldwide places like ${placeName} are planned on enquiry without invented rates.`,
    ],
  };
}
