import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const IMAGE =
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80";

/** @type {Array<[string, string, string, string, string, string, string, string[], number, string, string[]]>} */
const posts = [
  [
    "kodai-first-timer",
    "Kodaikanal for first-timers: a calm plan",
    "முதல் முறை கொடைக்கானல்: அமைதியான திட்டம்",
    "पहली बार कोडाइकनाल: शांत योजना",
    "How to see the best of Kodai without rushing every viewpoint in one day.",
    "ஒரே நாளில் எல்லா இடங்களையும் ஓடாமல் கொடையின் சிறப்பை காணும் வழி.",
    "एक दिन में सब जगह घूमे बिना कोडई का सर्वश्रेष्ठ कैसे देखें।",
    ["Guides", "First visit"],
    6,
    "2026-01-05",
    [
      "Kodaikanal rewards slow travel. Instead of stacking ten viewpoints into a single day, begin with the lake circuit and one gentle walk.",
      "Choose a stay slightly away from the busiest market lanes if you want quiet mornings. Private transfers make the climb from Madurai or Coimbatore far more comfortable.",
      "Canaan’s Kodai Escape and Kodai Complete packages are built around this pacing — curated, not crowded.",
    ],
  ],
  [
    "best-time-kodaikanal",
    "Best time to visit Kodaikanal",
    "கொடைக்கானல் செல்ல சிறந்த நேரம்",
    "कोडाइकनाल जाने का सबसे अच्छा समय",
    "Seasons, mist, and what each month feels like on the hills.",
    "பருவங்கள், மூடுபனி மற்றும் ஒவ்வொரு மாதத்தின் உணர்வு.",
    "मौसम, कोहरा और हर महीने पहाड़ियों का अहसास।",
    ["Seasons", "Guides"],
    5,
    "2026-01-08",
    [
      "April to June is popular for clear views and pleasant evenings. Monsoon months bring dramatic mist and fewer crowds, with occasional road caution.",
      "Winter mornings can be crisp — ideal for couples and photography if you pack warm layers.",
      "Tell us your preferred month when you enquire; we adjust stays and outdoor plans accordingly.",
    ],
  ],
  [
    "family-hill-packing",
    "Packing for a family hill trip",
    "குடும்ப மலை பயணத்திற்கான பொருட்கள்",
    "पारिवारिक पहाड़ी यात्रा के लिए पैकिंग",
    "Light layers, medicines, and the small things that save a day.",
    "இலகு அடுக்கு ஆடைகள், மருந்துகள் மற்றும் சிறிய உதவிகள்.",
    "हल्के लेयर, दवाइयाँ और छोटी ज़रूरी चीज़ें।",
    ["Family", "Tips"],
    4,
    "2026-01-12",
    [
      "Hills change temperature quickly. Pack light layers, a compact rain jacket, and comfortable walking shoes for everyone.",
      "Carry basic medicines, snacks for children, and power banks — network can be patchy on some stretches.",
      "Our Kodai Family package keeps daily plans flexible so packing stays practical rather than excessive.",
    ],
  ],
  [
    "honeymoon-kodai",
    "A honeymoon rhythm in Kodaikanal",
    "கொடைக்கானலில் தேனிலவு தாளம்",
    "कोडाइकनाल में हनीमून लय",
    "Private evenings, soft mornings, and views worth lingering for.",
    "தனியார் மாலைகள், மென்மையான காலைகள்.",
    "निजी शामें और धीमी सुबहें।",
    ["Honeymoon", "Couples"],
    5,
    "2026-01-15",
    [
      "Honeymoon travel works best when the itinerary leaves white space — time for quiet breakfasts and unhurried viewpoints.",
      "Choose a stay with privacy and valley light. Add one special dinner and one private experience rather than a packed checklist.",
      "Kodai Honeymoon and Kodai Luxury are designed around that rhythm.",
    ],
  ],
  [
    "kodai-lake-guide",
    "Kodaikanal Lake: how to enjoy it slowly",
    "கொடைக்கானல் ஏரி: மெதுவாக அனுபவிக்க",
    "कोडाइकनाल झील: धीरे आनंद लें",
    "Boating, walks, and the quiet corners of the star-shaped lake.",
    "படகு, நடை மற்றும் ஏரியின் அமைதியான மூலைகள்.",
    "बोटिंग, सैर और झील के शांत कोने।",
    ["Places", "Lake"],
    5,
    "2026-01-18",
    [
      "The lake is the heart of town. Early mornings are softer — fewer boats, cooler air, and better light for photographs.",
      "Walk a stretch of the lake road, pause for tea, then take a short boat ride instead of trying to “finish” the circuit in a rush.",
      "If you stay nearby, return at dusk when the water holds the last gold of the day.",
    ],
  ],
  [
    "coakers-walk-guide",
    "Coaker's Walk at golden hour",
    "கோக்கர்ஸ் வாக் பொன் நேரத்தில்",
    "कोकर्स वॉक गोल्डन आवर में",
    "Mist, valley light, and why timing matters on this famous path.",
    "மூடுபனி, பள்ளத்தாக்கு ஒளி — நேரம் ஏன் முக்கியம்.",
    "कोहरा, घाटी की रोशनी — समय क्यों मायने रखता है।",
    ["Places", "Walks"],
    4,
    "2026-01-22",
    [
      "Coaker’s Walk is short, but the mood changes with the hour. Late afternoon often brings valley glow and moving mist.",
      "Wear a light jacket — wind can rise quickly along the railing. Keep phones secured near the edge.",
      "Pair it with Bryant Park or the lake rather than stacking cliff viewpoints the same evening.",
    ],
  ],
  [
    "dolphins-nose-trek",
    "Dolphin's Nose: a careful trek guide",
    "டால்பின் நோஸ்: கவனமான ட்ரெக் வழிகாட்டி",
    "डॉल्फिन नोज़: सावधान ट्रेक गाइड",
    "What to wear, when to go, and how to respect the cliff edge.",
    "என்ன அணிய வேண்டும், எப்போது செல்ல வேண்டும்.",
    "क्या पहनें, कब जाएँ, और चट्टान का सम्मान कैसे करें।",
    ["Places", "Trek"],
    6,
    "2026-01-25",
    [
      "Dolphin’s Nose is dramatic — and it demands respect. Go with proper shoes, daylight, and a guide if the path feels unfamiliar.",
      "Avoid the edge in heavy mist or after rain. The view is enough; you do not need to lean for a photo.",
      "Build recovery time into the day. This is a highlight, not a stop between five other cliff points.",
    ],
  ],
  [
    "berijam-lake-permit",
    "Berijam Lake and the forest permit",
    "பெரியம் ஏரி மற்றும் வன அனுமதி",
    "बेरिजाम झील और वन परमिट",
    "How forest permits work and what makes Berijam feel untouched.",
    "வன அனுமதி எப்படி வேலை செய்கிறது.",
    "वन परमिट कैसे काम करता है और बेरिजाम क्यों अनछुआ लगता है।",
    ["Places", "Nature"],
    5,
    "2026-01-28",
    [
      "Berijam sits inside protected forest. Permits and vehicle limits exist to keep the place quiet and wild.",
      "Plan this as a morning outing with a trusted local driver who knows the permit process.",
      "Carry water, skip litter, and leave the silence intact — that is the real luxury of Berijam.",
    ],
  ],
  [
    "pine-forest-walk",
    "Walking the pine forests of Kodai",
    "கொடையின் பைன் காடுகளில் நடை",
    "कोडई के पाइन जंगलों में सैर",
    "Cool shade, soft needles underfoot, and photo-ready aisles of green.",
    "குளிர் நிழல், மென்மையான ஊசி இலைகள்.",
    "ठंडी छाँव और हरे गलियारे।",
    ["Places", "Nature"],
    4,
    "2026-02-01",
    [
      "Pine forests are Kodai’s softest rooms. The air cools, sound drops, and the light becomes striped and gentle.",
      "Keep walks short if travelling with children or elders. Stay on known paths and respect private land.",
      "After rain, needles can be slippery — slow steps make better memories than rushed photos.",
    ],
  ],
  [
    "silver-cascade-visit",
    "Silver Cascade: short stop, big mood",
    "சில்வர் கேஸ்கேட்: சிறிய நிறுத்தம், பெரிய உணர்வு",
    "सिल्वर कैस्केड: छोटा पड़ाव, बड़ा मूड",
    "Best viewing points on the way into town and monsoon caution.",
    "நகருக்குள் வரும் வழியில் சிறந்த பார்வை.",
    "शहर के रास्ते बेहतरीन नज़ारा और मानसून सावधानी।",
    ["Places", "Waterfalls"],
    3,
    "2026-02-04",
    [
      "Silver Cascade greets many travellers on the climb into town. It is a short stop that still sets the hill mood.",
      "In monsoon the fall is fuller — also wetter underfoot. Stay behind safe viewing areas.",
      "Use it as a welcome pause, then continue to your stay without turning arrival day into a full tour.",
    ],
  ],
  [
    "poombarai-village",
    "Poombarai village and the valley farms",
    "பூம்பராய் கிராமம் மற்றும் பள்ளத்தாக்கு பண்ணைகள்",
    "पूमबराई गाँव और घाटी के खेत",
    "Terraced green, quiet lanes, and a slower Kodai beyond the market.",
    "படிநிலை பசுமை, அமைதியான தெருக்கள்.",
    "सीढ़ीदार हरियाली और बाज़ार से परे शांत कोडई।",
    ["Places", "Villages"],
    5,
    "2026-02-08",
    [
      "Poombarai shows another face of Kodai — terraces, farm air, and lanes that feel far from souvenir shops.",
      "Go for the drive and the openness, not for a checklist of attractions. Sit with the view.",
      "Combine with Mannavanur on longer itineraries when you want space more than town buzz.",
    ],
  ],
  [
    "mannavanur-lake",
    "Mannavanur: open sky and still water",
    "மன்னவனூர்: திறந்த வானம், அமைதியான நீர்",
    "मन्नवनूर: खुला आसमान और शांत पानी",
    "A longer drive for space, silence, and soft hills.",
    "வெளி, அமைதி மற்றும் மென்மையான மலைகள்.",
    "खुली जगह, सन्नाटा और नरम पहाड़ियाँ।",
    ["Places", "Nature"],
    5,
    "2026-02-11",
    [
      "Mannavanur rewards those who leave the centre. The lake and surrounding hills feel open and unhurried.",
      "Pack snacks, start early, and keep expectations gentle — this is atmosphere travel.",
      "On Canaan longer packages, we place this on a day with room to breathe.",
    ],
  ],
  [
    "pillar-rocks-viewpoint",
    "Pillar Rocks without the rush",
    "பில்லர் ராக்ஸ் அவசரமின்றி",
    "पिलर रॉक्स बिना हड़बड़ी",
    "Arrive early, stay for the mist to move, leave before peak crowds.",
    "காலை சீக்கிரம் வாருங்கள், மூடுபனி நகரட்டும்.",
    "सुबह जल्दी आएँ, कोहरा हटने दें।",
    ["Places", "Viewpoints"],
    4,
    "2026-02-14",
    [
      "Pillar Rocks is iconic — and crowded at midday. Early hours give you mist, space, and cleaner photos.",
      "If fog is thick, wait a little. Kodai often reveals the pillars in sudden clearings.",
      "Pair with Green Valley or a pine stop rather than forcing every viewpoint before lunch.",
    ],
  ],
  [
    "green-valley-view",
    "Green Valley View: soft light and space",
    "கிரீன் வேலி வியூ: மென்மையான ஒளி",
    "ग्रीन वैली व्यू: कोमल रोशनी",
    "A quieter lookout when you want air more than a checklist.",
    "பட்டியலை விட காற்று வேண்டும்போது.",
    "चेकलिस्ट से ज़्यादा हवा चाहिए तो यहाँ।",
    ["Places", "Viewpoints"],
    3,
    "2026-02-17",
    [
      "Green Valley View is for breathing. Wide green, soft light, and fewer hard edges than cliff trails.",
      "It works well for families and elders who want a view without a long trek.",
      "Bring a jacket — valley wind can cool quickly even on bright days.",
    ],
  ],
  [
    "bryant-park-morning",
    "Bryant Park in the morning calm",
    "பிரையண்ட் பார்க் காலை அமைதியில்",
    "ब्रायंट पार्क सुबह की शांति में",
    "Flowers, lake edge, and a gentle start before the town wakes.",
    "மலர்கள், ஏரி விளிம்பு, மென்மையான தொடக்கம்.",
    "फूल, झील किनारा, शहर के जागने से पहले।",
    ["Places", "Parks"],
    4,
    "2026-02-20",
    [
      "Bryant Park is loveliest before the day fills up. Flowers look fresher and the lake edge feels private.",
      "It is an easy win for children and a soft start for couples on honeymoon days.",
      "Combine with a lake walk and breakfast rather than racing to distant cliffs first thing.",
    ],
  ],
  [
    "upper-lake-view",
    "Upper Lake View for first light",
    "அப்பர் லேக் வியூ முதல் ஒளிக்கு",
    "अपर लेक व्यू पहली रोशनी के लिए",
    "Soft horizons and why photographers love this angle.",
    "மென்மையான எல்லைகள் — புகைப்படக்காரர்கள் ஏன் விரும்புகிறார்கள்.",
    "कोमल क्षितिज — फोटोग्राफर क्यों पसंद करते हैं।",
    ["Places", "Photography"],
    4,
    "2026-02-23",
    [
      "Upper Lake View gives a wider read of Kodai’s water and hills — especially in soft first light.",
      "Arrive with time to spare. Mist may lift slowly; patience is part of the frame.",
      "Keep noise low. This is a place people come to feel, not to shout over the valley.",
    ],
  ],
  [
    "guna-caves-history",
    "Guna Caves: history, lore, and caution",
    "குணா குகைகள்: வரலாறு மற்றும் எச்சரிக்கை",
    "गुना केव्स: इतिहास और सावधानी",
    "What you can see from safe viewpoints and what to skip.",
    "பாதுகாப்பான இடங்களில் இருந்து என்ன பார்க்கலாம்.",
    "सुरक्षित जगहों से क्या देखें और क्या छोड़ें।",
    ["Places", "History"],
    5,
    "2026-02-26",
    [
      "Guna Caves carry film lore and real risk. Respect barriers and official guidance at all times.",
      "Enjoy the surrounding viewpoints and pine shade instead of seeking unsafe edges.",
      "A good Kodai day is measured by memory and safety — never by dangerous photos.",
    ],
  ],
  [
    "kodai-food-trail",
    "A simple Kodaikanal food trail",
    "எளிய கொடைக்கானல் உணவு பாதை",
    "सरल कोडाइकनाल फूड ट्रेल",
    "Homestyle meals, warm drinks, and where to eat without fuss.",
    "வீட்டு உணவு, சூடான பானங்கள்.",
    "घर जैसा खाना और बिना झंझट खाने की जगहें।",
    ["Food", "Guides"],
    5,
    "2026-03-01",
    [
      "Kodai food is comfort more than spectacle — hot meals, simple flavours, and warm drinks after misty walks.",
      "Ask your host for homestyle recommendations. Local bakers and small cafés often beat busy tourist strips.",
      "Canaan stays can include meal guidance so you spend less time searching and more time resting.",
    ],
  ],
  [
    "homemade-chocolates",
    "Homemade chocolates and what to buy",
    "வீட்டில் தயாரித்த சாக்லேட் வாங்க",
    "होममेड चॉकलेट क्या खरीदें",
    "Fresh batches, fair prices, and gifts that actually travel well.",
    "புதிய பேட்ச், நியாய விலை.",
    "ताज़ी खेप, सही कीमत, और अच्छे तोहफे।",
    ["Food", "Shopping"],
    3,
    "2026-03-04",
    [
      "Homemade chocolate shops are part of Kodai’s charm. Choose fresh batches and flavours you will finish.",
      "Compare a few counters before buying in bulk. Quality varies more than the labels suggest.",
      "Keep chocolates cool on the descent — heat from the plains can soften soft centres quickly.",
    ],
  ],
  [
    "eucalyptus-oil-shopping",
    "Eucalyptus oil and local shopping sense",
    "யூகலிப்டஸ் எண்ணெய் மற்றும் உள்ளூர் வாங்குதல்",
    "यूकेलिप्टस तेल और लोकल खरीदारी",
    "How to choose quality bottles and skip tourist traps.",
    "தரமான பாட்டில்களை எப்படி தேர்வு செய்வது.",
    "क्वालिटी बोतल कैसे चुनें।",
    ["Shopping", "Tips"],
    3,
    "2026-03-07",
    [
      "Eucalyptus oil is a classic Kodai takeaway. Buy sealed bottles from trusted counters, not unmarked street pours.",
      "One good bottle is better than three doubtful ones. Ask about purity and storage.",
      "Pair shopping with a lake evening so the day does not become only markets.",
    ],
  ],
  [
    "how-to-reach-kodai",
    "How to reach Kodaikanal the easy way",
    "கொடைக்கானல் எளிதாக செல்ல",
    "कोडाइकनाल आसानी से कैसे पहुँचें",
    "Madurai, Coimbatore, and why private transfers change the climb.",
    "மதுரை, கோவை — தனியார் பயணம் ஏன் மாற்றுகிறது.",
    "मदुरै, कोयंबटूर — प्राइवेट ट्रांसफर क्यों आसान बनाता है।",
    ["Travel", "Guides"],
    6,
    "2026-03-10",
    [
      "Most travellers approach via Madurai or Coimbatore, then climb into the hills by road.",
      "Private transfers reduce stress on hairpin bends — especially with elders, children, or late arrivals.",
      "Share flight or train times in your Canaan enquiry; we align pickup so arrival feels soft, not rushed.",
    ],
  ],
  [
    "madurai-to-kodai",
    "Madurai to Kodaikanal road guide",
    "மதுரையிலிருந்து கொடைக்கானல் சாலை",
    "मदुरै से कोडाइकनाल रोड गाइड",
    "Curves, stops, and a calmer arrival into the mist.",
    "வளைவுகள், நிறுத்தங்கள், அமைதியான வருகை.",
    "मोड़, पड़ाव और कोहरे में शांत आगमन।",
    ["Travel", "Guides"],
    5,
    "2026-03-13",
    [
      "The Madurai climb is scenic and winding. Motion-sensitive travellers should keep snacks light and breaks sensible.",
      "Silver Cascade often appears near arrival — a natural pause before you settle into your stay.",
      "Night drives need extra care in fog. Daylight arrivals are kinder for first visits.",
    ],
  ],
  [
    "coimbatore-to-kodai",
    "Coimbatore to Kodaikanal: route notes",
    "கோவையிலிருந்து கொடைக்கானல் வழி",
    "कोयंबटूर से कोडाइकनाल रूट नोट्स",
    "Timing, weather, and comfort tips for the hill climb.",
    "நேரம், வானிலை, வசதி குறிப்புகள்.",
    "समय, मौसम और आराम के टिप्स।",
    ["Travel", "Guides"],
    5,
    "2026-03-16",
    [
      "Coimbatore is a common gateway for flyers. Build buffer time between landing and the hill drive.",
      "Weather on the climb can shift quickly — jackets in the car matter even on warm plains mornings.",
      "Canaan can arrange door-to-door comfort so the first mist you feel is welcome, not stressful.",
    ],
  ],
  [
    "kodai-weather-month",
    "Kodaikanal weather month by month",
    "மாதந்தோறும் கொடை வானிலை",
    "कोडाइकनाल मौसम महीने दर महीने",
    "What to expect from January through December on the hills.",
    "ஜனவரி முதல் டிசம்பர் வரை என்ன எதிர்பார்க்கலாம்.",
    "जनवरी से दिसंबर तक क्या उम्मीद करें।",
    ["Seasons", "Guides"],
    7,
    "2026-03-19",
    [
      "Winter brings crisp mornings. Summer offers cool evenings against plains heat. Monsoon paints the hills deep green.",
      "No month is “wrong” — each asks for different packing and pacing.",
      "Tell us your dates; we shape outdoor plans around likely mist, rain, and daylight.",
    ],
  ],
  [
    "monsoon-in-kodai",
    "Monsoon in Kodaikanal: drama and care",
    "கொடையில் மழைக்காலம்: அழகு மற்றும் கவனம்",
    "मानसून कोडाइकनाल: नाटक और सावधानी",
    "Lush hills, slippery paths, and how to plan around rain.",
    "பசுமை, வழுக்கும் பாதைகள், மழை திட்டம்.",
    "हरियाली, फिसलन भरे रास्ते, बारिश की योजना।",
    ["Seasons", "Tips"],
    5,
    "2026-03-22",
    [
      "Monsoon Kodai is cinematic — thick mist, loud waterfalls, empty-looking roads between showers.",
      "Choose indoor-friendly stays, waterproof shoes, and flexible viewpoint plans.",
      "Avoid cliff edges after rain. Beauty stays; risk does not need to.",
    ],
  ],
  [
    "winter-in-kodai",
    "Winter mornings in the Princess of Hills",
    "மலை இளவரசியின் குளிர்கால காலைகள்",
    "पहाड़ियों की रानी की सर्द सुबहें",
    "Crisp air, warm layers, and quiet lake circuits.",
    "குளிர் காற்று, சூடான ஆடைகள், அமைதியான ஏரி.",
    "ठंडी हवा, गर्म कपड़े, शांत झील सर्किट।",
    ["Seasons", "Couples"],
    4,
    "2026-03-25",
    [
      "Winter Kodai is for warm jackets and slow lake circuits. Mornings can feel sharper than the plains expect.",
      "Couples often love this season for quieter evenings and soft light.",
      "Pack layers you can add and remove — hill temperatures swing through the day.",
    ],
  ],
  [
    "summer-escape-kodai",
    "Summer escape: cool evenings in Kodai",
    "கோடை தப்பித்தல்: கொடையின் குளிர் மாலைகள்",
    "गर्मी से राहत: कोडई की ठंडी शामें",
    "Why April–June still feels like a soft reset from the plains.",
    "ஏப்ரல்–ஜூன் இன்னும் மென்மையான ஓய்வு.",
    "अप्रैल–जून मैदानों से राहत जैसा क्यों लगता है।",
    ["Seasons", "Family"],
    4,
    "2026-03-28",
    [
      "When the plains burn, Kodai evenings still invite a walk and a jacket.",
      "Book stays earlier in peak school holidays. Popular weekends fill fast.",
      "Family packages work well in summer when days are longer and plans can stay outdoor-friendly.",
    ],
  ],
  [
    "weekend-getaway-kodai",
    "Perfect weekend getaway to Kodaikanal",
    "கொடைக்கானல் வார இறுதி தப்பித்தல்",
    "कोडाइकनाल वीकेंड गेटअवे",
    "A 2-night plan that feels complete without exhaustion.",
    "சோர்வில்லாமல் முழுமையான 2 இரவு திட்டம்.",
    "थके बिना पूरा लगता 2-रात प्लान।",
    ["Itinerary", "Guides"],
    5,
    "2026-04-01",
    [
      "A weekend works if you protect arrival evening as rest. Do not force viewpoints after a long climb.",
      "Day two: lake + one walk + one viewpoint. Day three: soft morning and descent.",
      "Kodai Escape is shaped for this exact rhythm.",
    ],
  ],
  [
    "two-day-kodai-itinerary",
    "2-day Kodaikanal itinerary",
    "2 நாள் கொடைக்கானல் திட்டம்",
    "2-दिन का कोडाइकनाल itinerary",
    "Lake, one viewpoint, one forest — paced for real rest.",
    "ஏரி, ஒரு காட்சி, ஒரு காடு — உண்மையான ஓய்வு.",
    "झील, एक व्यूपॉइंट, एक जंगल — असली आराम।",
    ["Itinerary", "Guides"],
    6,
    "2026-04-04",
    [
      "Day 1: settle, lake circuit, Coaker’s Walk if energy remains. Day 2: pine forest and one major viewpoint.",
      "Skip trying to “cover” Berijam and Dolphin’s Nose and Pillar Rocks in 48 hours.",
      "Enquire with your dates — we trim the plan to your group’s real pace.",
    ],
  ],
  [
    "three-day-kodai-itinerary",
    "3-day Kodaikanal itinerary",
    "3 நாள் கொடைக்கானல் திட்டம்",
    "3-दिन का कोडाइकनाल itinerary",
    "Add Berijam or Poombarai without turning the trip into a race.",
    "பெரியம் அல்லது பூம்பராய் சேர்த்து அவசரமில்லாமல்.",
    "बेरिजाम या पूमबराई जोड़ें बिना दौड़ बनाए।",
    ["Itinerary", "Guides"],
    7,
    "2026-04-07",
    [
      "Three days let you keep town comfort and still reach a quieter outer lake or village road.",
      "Keep one half-day fully open. Mist and mood often rewrite the best plan.",
      "Kodai Complete is built for this balanced middle length.",
    ],
  ],
  [
    "five-day-kodai-itinerary",
    "5-day Kodaikanal deep stay",
    "5 நாள் கொடை ஆழமான தங்கல்",
    "5-दिन का गहरा कोडई प्रवास",
    "Enough time for mist mornings, village roads, and true quiet.",
    "மூடுபனி காலைகள், கிராம சாலைகள், உண்மையான அமைதி.",
    "कोहरे वाली सुबहें, गाँव की सड़कें, असली शांति।",
    ["Itinerary", "Luxury"],
    8,
    "2026-04-10",
    [
      "Five days is when Kodai stops feeling like a tour and starts feeling like a stay.",
      "You can repeat the lake at different hours, add camping or Berijam, and still rest.",
      "Luxury and longer Canaan packages leave white space on purpose.",
    ],
  ],
  [
    "kodai-with-kids",
    "Kodaikanal with kids: gentle plans",
    "குழந்தைகளுடன் கொடை: மென்மையான திட்டம்",
    "बच्चों के साथ कोडाइकनाल",
    "Short walks, snack stops, and stays that keep evenings easy.",
    "குறுகிய நடைகள், சிற்றுண்டி, எளிய மாலைகள்.",
    "छोटी सैर, स्नैक्स, आसान शामें।",
    ["Family", "Tips"],
    5,
    "2026-04-13",
    [
      "Kids enjoy Kodai when days are short and snack-friendly. Lake, park, and pine shade beat long cliff hikes.",
      "Choose stays with easy dining and warm water. Evenings matter as much as viewpoints.",
      "Our family package pacing is designed around naps, moods, and early nights.",
    ],
  ],
  [
    "kodai-with-elders",
    "Kodaikanal with elders: comfort first",
    "பெரியவர்களுடன் கொடை: வசதி முதல்",
    "बुजुर्गों के साथ कोडई: आराम पहले",
    "Fewer steps, warmer layers, and viewpoints with easy access.",
    "குறைந்த படிகள், சூடான ஆடைகள்.",
    "कम सीढ़ियाँ, गर्म कपड़े, आसान व्यूपॉइंट।",
    ["Family", "Tips"],
    5,
    "2026-04-16",
    [
      "Focus on lake roads, park walks, and viewpoints with vehicle access. Skip steep treks.",
      "Keep medicines organised and driving days shorter. Comfort is the itinerary.",
      "Private transfers and ground-floor or lift-friendly stays make a real difference.",
    ],
  ],
  [
    "kodai-photography-spots",
    "Best photography spots in Kodaikanal",
    "கொடையில் சிறந்த புகைப்பட இடங்கள்",
    "कोडाइकनाल के बेस्ट फोटो स्पॉट",
    "Light, mist, and compositions that feel cinematic.",
    "ஒளி, மூடுபனி, சினிமா உணர்வு.",
    "रोशनी, कोहरा और सिनेमैटिक फ्रेम।",
    ["Photography", "Places"],
    6,
    "2026-04-19",
    [
      "Kodai photographs best in soft light — early morning and late afternoon — when mist becomes texture.",
      "Lake edges, pine aisles, and valley lookouts give different moods without needing risky edges.",
      "Protect gear from sudden drizzle. A simple rain cover saves a day.",
    ],
  ],
  [
    "sunrise-kodai",
    "Where to catch sunrise in Kodai",
    "கொடையில் சூரிய உதயம் எங்கே",
    "कोडई में सूर्योदय कहाँ देखें",
    "Early starts, warm jackets, and soft first light.",
    "காலை எழுச்சி, சூடான ஜாக்கெட்.",
    "जल्दी उठना, गरम जैकेट, कोमल पहली रोशनी।",
    ["Photography", "Tips"],
    4,
    "2026-04-22",
    [
      "Sunrise in Kodai is about being present more than chasing the perfect spot. Choose one lookout and arrive early.",
      "Carry warm layers and a flask. Waiting is part of the ritual.",
      "If mist hides the sun, stay — the reveal is often better than a clear horizon.",
    ],
  ],
  [
    "sunset-kodai",
    "Sunset viewpoints worth the wait",
    "சூரிய அஸ்தமன காட்சிகள்",
    "सूर्यास्त व्यूपॉइंट जो इंतज़ार के लायक",
    "Valley glow, cloud play, and arriving before the crowd.",
    "பள்ளத்தாக்கு ஒளி, மேக நாடகம்.",
    "घाटी की चमक और भीड़ से पहले पहुँचना।",
    ["Photography", "Places"],
    4,
    "2026-04-25",
    [
      "Sunset crowds gather fast. Arrive 40–60 minutes early for space and a calmer frame.",
      "Coaker’s Walk and select valley views often glow longer than the sun itself.",
      "Leave before darkness on unfamiliar roads — dusk driving in mist needs care.",
    ],
  ],
  [
    "night-camping-kodai",
    "Night camping near Kodaikanal",
    "கொடை அருகில் இரவு முகாம்",
    "कोडाइकनाल के पास नाइट कैंपिंग",
    "Stars, campfire warmth, and safety basics for the hills.",
    "நட்சத்திரங்கள், நெருப்பு சூடு, பாதுகாப்பு.",
    "सितारे, अलाव की गर्माहट, पहाड़ी सुरक्षा।",
    ["Experiences", "Adventure"],
    6,
    "2026-04-28",
    [
      "Camping near Kodai is about sky and silence. Go with organised setups that know local rules and weather.",
      "Warm layers, closed shoes, and respecting forest guidelines keep the night safe.",
      "Ask Canaan about camping add-ons on longer packages when the forecast is clear.",
    ],
  ],
  [
    "boating-kodai-lake",
    "Boating on Kodaikanal Lake",
    "கொடைக்கானல் ஏரியில் படகு",
    "कोडाइकनाल झील पर बोटिंग",
    "Best hours, ticket tips, and making it feel unhurried.",
    "சிறந்த நேரம், டிக்கெட் குறிப்புகள்.",
    "बेस्ट समय और बिना जल्दबाज़ी का अनुभव।",
    ["Experiences", "Lake"],
    3,
    "2026-05-01",
    [
      "Boating is simple joy. Morning slots usually feel quieter and cooler.",
      "Keep the ride short if children get restless — the memory is the water, not the duration.",
      "Combine with a lakeside walk so the lake day feels complete.",
    ],
  ],
  [
    "cycling-around-kodai",
    "Cycling around Kodaikanal",
    "கொடைக்கானலை சுற்றி சைக்கிள்",
    "कोडाइकनाल के आसपास साइक्लिंग",
    "Gentle loops, road sense, and when to leave the bike behind.",
    "மென்மையான வழிகள், சாலை விழிப்பு.",
    "हल्के लूप और कब साइकिल छोड़ें।",
    ["Experiences", "Active"],
    4,
    "2026-05-04",
    [
      "Cycling works on gentler town loops when traffic is lighter. Wear visible colours and slow near bends.",
      "Skip steep cliff roads on bikes if you are new to hill riding.",
      "Mist reduces visibility — if you cannot see far, walk instead.",
    ],
  ],
  [
    "horse-riding-kodai",
    "Horse riding in the hills",
    "மலைகளில் குதிரை சவாரி",
    "पहाड़ियों में घुड़सवारी",
    "What to expect, fair pricing, and kinder ways to ride.",
    "என்ன எதிர்பார்க்கலாம், நியாய விலை.",
    "क्या उम्मीद करें और सही तरीका।",
    ["Experiences", "Family"],
    3,
    "2026-05-07",
    [
      "Horse rides are offered in popular stretches. Agree on price and duration clearly before you mount.",
      "Choose calmer animals for children and keep rides short.",
      "Treat animals kindly — a gentle experience beats a rushed photo loop.",
    ],
  ],
  [
    "best-stays-kodai",
    "How to choose a stay in Kodaikanal",
    "கொடையில் தங்கும் இடம் எப்படி தேர்வு",
    "कोडाइकनाल में ठहरना कैसे चुनें",
    "Lake edge vs quiet outskirts — match stay to your trip mood.",
    "ஏரி அருகில் vs அமைதியான புறநகர்.",
    "झील किनारा बनाम शांत बाहरी इलाका।",
    ["Stays", "Guides"],
    5,
    "2026-05-10",
    [
      "Lake-side stays put you in the centre of walks and cafés. Outskirts give quieter nights and wider views.",
      "Ask about heating, hot water, parking, and how fog affects access to your property.",
      "Canaan matches stay type to package mood — honeymoon privacy differs from family convenience.",
    ],
  ],
  [
    "quiet-stays-away-market",
    "Quiet stays away from the market buzz",
    "சந்தை சத்தத்திற்கு அப்பால் அமைதியான தங்கல்",
    "बाज़ार शोर से दूर शांत ठहराव",
    "Why a little distance gives you better mornings.",
    "சிறிய தூரம் சிறந்த காலைகளைத் தரும்.",
    "थोड़ी दूरी बेहतर सुबह देती है।",
    ["Stays", "Tips"],
    4,
    "2026-05-13",
    [
      "Market energy is fun for an hour and tiring all night. A short drive away often restores the hill feeling.",
      "Quiet stays suit couples, writers, and anyone coming to rest.",
      "We can still plan town moments — you just sleep away from the noise.",
    ],
  ],
  [
    "kodai-budget-tips",
    "Budget tips for a Kodai trip",
    "கொடை பயணத்திற்கான பட்ஜெட் குறிப்புகள்",
    "कोडई ट्रिप के बजट टिप्स",
    "Save on the right things without losing the hill feeling.",
    "சரியான இடத்தில் சேமித்து மலை உணர்வை இழக்காதீர்கள்.",
    "सही जगह बचत करें, पहाड़ी अहसास न खोएँ।",
    ["Budget", "Tips"],
    5,
    "2026-05-16",
    [
      "Spend on safe transfer and a decent stay. Save on random souvenir runs and unnecessary add-ons.",
      "Eat simple local meals. Not every evening needs a tourist restaurant.",
      "A shorter, well-paced trip beats a cheap trip that feels exhausting.",
    ],
  ],
  [
    "luxury-kodai-trip",
    "A luxury Kodaikanal trip, done quietly",
    "ஆடம்பர கொடை பயணம் அமைதியாக",
    "लक्ज़री कोडई ट्रिप, शांत अंदाज़ में",
    "Private transfers, spacious stays, and unhurried evenings.",
    "தனியார் பயணம், விசால தங்கல்.",
    "प्राइवेट ट्रांसफर, विशाल ठहराव, धीमी शामें।",
    ["Luxury", "Couples"],
    5,
    "2026-05-19",
    [
      "Luxury in Kodai is quiet: space, privacy, timing, and someone else handling the climb.",
      "Choose stays with view and silence. Let dinners be slow. Let mornings be unplanned.",
      "Kodai Luxury with Canaan is built around that soft standard.",
    ],
  ],
  [
    "solo-travel-kodai",
    "Solo travel in Kodaikanal",
    "தனியாக கொடைக்கானல் பயணம்",
    "कोडाइकनाल में सोलो ट्रैवल",
    "Safe pacing, good coffee, and days shaped only by you.",
    "பாதுகாப்பான வேகம், நல்ல காபி.",
    "सुरक्षित रफ्तार और सिर्फ आपके हिसाब के दिन।",
    ["Solo", "Guides"],
    5,
    "2026-05-22",
    [
      "Solo Kodai is excellent for walking, journaling, and photography. Stick to daylight for remote edges.",
      "Share your stay details with someone at home. Use trusted taxis for outer points.",
      "Build days around one place deeply rather than many places thinly.",
    ],
  ],
  [
    "couple-romantic-kodai",
    "Romantic ideas for couples in Kodai",
    "ஜோடிகளுக்கான காதல் யோசனைகள்",
    "कपल के लिए रोमांटिक आइडिया",
    "Private viewpoints, slow dinners, and shared mist walks.",
    "தனியார் காட்சிகள், மெதுவான இரவு உணவு.",
    "निजी व्यूपॉइंट, धीमी डिनर, साथ में कोहरा।",
    ["Couples", "Honeymoon"],
    4,
    "2026-05-25",
    [
      "Romance here is atmospheric — shared jackets on Coaker’s Walk, quiet lake evenings, pine shade picnics.",
      "Book one private experience and leave the rest open. Over-planning kills the mood.",
      "Honeymoon packages keep the checklist short on purpose.",
    ],
  ],
  [
    "group-trip-kodai",
    "Planning a group trip to Kodaikanal",
    "குழுவுடன் கொடைக்கானல் திட்டம்",
    "ग्रुप ट्रिप कोडाइकनाल प्लान",
    "Vehicles, rooms, and how to keep everyone happy.",
    "வாகனங்கள், அறைகள், அனைவரையும் மகிழ்விக்க.",
    "वाहन, कमरे, और सबको खुश रखना।",
    ["Group", "Guides"],
    6,
    "2026-05-28",
    [
      "Groups need clear vehicle plans and rooming lists before arrival. Hills punish last-minute chaos.",
      "Agree on a pace leader. Not every person needs every viewpoint.",
      "Canaan can coordinate multi-room stays and shared transfers for friends or extended family.",
    ],
  ],
  [
    "what-to-pack-kodai",
    "What to pack for Kodaikanal",
    "கொடைக்கானலுக்கு என்ன எடுக்க வேண்டும்",
    "कोडाइकनाल के लिए क्या पैक करें",
    "Layers, shoes, rain cover — a practical checklist.",
    "அடுக்கு ஆடைகள், காலணிகள், மழை கவர்.",
    "लेयर, जूते, रेन कवर — प्रैक्टिकल लिस्ट।",
    ["Tips", "Packing"],
    4,
    "2026-06-01",
    [
      "Pack layers, walking shoes with grip, a compact rain jacket, and a warm sleep layer for winter.",
      "Add sunscreen, lip balm, basic medicines, and a power bank.",
      "Leave space in the bag for chocolates and oil — you will buy something.",
    ],
  ],
  [
    "safety-tips-kodai",
    "Hill safety tips for Kodaikanal",
    "கொடைக்கானல் மலை பாதுகாப்பு குறிப்புகள்",
    "कोडाइकनाल पहाड़ी सुरक्षा टिप्स",
    "Fog, edges, driving, and looking after each other.",
    "மூடுபனி, விளிம்புகள், ஓட்டம்.",
    "कोहरा, किनारे, ड्राइविंग और एक-दूसरे का ध्यान।",
    ["Tips", "Safety"],
    5,
    "2026-06-04",
    [
      "Fog reduces visibility on roads and viewpoints. Slow down. Selfies are never worth a cliff edge.",
      "Use trusted drivers for night and outer forest routes.",
      "Keep children close at railings and water edges. The hills are beautiful when respected.",
    ],
  ],
  [
    "local-markets-kodai",
    "Local markets and thoughtful shopping",
    "உள்ளூர் சந்தைகள் மற்றும் சிந்தனைமிக்க வாங்குதல்",
    "लोकल मार्केट और सोच-समझकर खरीदारी",
    "Spices, oils, woollens — buy what you will actually use.",
    "மசாலா, எண்ணெய், கம்பளி — பயன்படுத்தும் பொருட்கள்.",
    "मसाले, तेल, ऊन — जो सच में काम आए।",
    ["Shopping", "Guides"],
    4,
    "2026-06-07",
    [
      "Markets are lively. Decide a budget before you enter and stick to useful gifts.",
      "Check seals on oils and freshness on chocolates. Bargain politely.",
      "Shop after a viewpoint day so markets feel like a bonus, not the whole trip.",
    ],
  ],
  [
    "temples-near-kodai",
    "Quiet temples and prayer stops near Kodai",
    "கொடை அருகில் அமைதியான கோயில்கள்",
    "कोडई के पास शांत मंदिर",
    "Gentle pauses for reflection between misty viewpoints.",
    "மூடுபனி காட்சிகளுக்கு இடையே அமைதியான நிறுத்தம்.",
    "कोहरे वाले व्यूपॉइंट के बीच शांत ठहराव।",
    ["Culture", "Places"],
    4,
    "2026-06-10",
    [
      "Small temples and prayer stops around Kodai offer quiet between scenic drives.",
      "Dress modestly, keep voices low, and follow local custom.",
      "These pauses often become unexpected favourites on family trips.",
    ],
  ],
  [
    "waterfall-circuit-kodai",
    "Waterfall circuit around Kodaikanal",
    "கொடைக்கானல் சுற்றி அருவி சுற்று",
    "कोडाइकनाल वॉटरफॉल सर्किट",
    "Silver Cascade and beyond — how to sequence falls wisely.",
    "சில்வர் கேஸ்கேட் மற்றும் அதற்கு அப்பால்.",
    "सिल्वर कैस्केड और आगे — सही क्रम।",
    ["Places", "Waterfalls"],
    5,
    "2026-06-13",
    [
      "Waterfalls look strongest after rain, but paths can be slick. Sequence stops with daylight and road safety in mind.",
      "One or two falls done calmly beat five rushed photos.",
      "Ask your driver which falls are accessible on your travel day.",
    ],
  ],
  [
    "mist-and-magic-kodai",
    "Mist and magic: why Kodai feels cinematic",
    "மூடுபனியும் மாயமும்: கொடை ஏன் சினிமா",
    "कोहरा और जादू: कोडई सिनेमा जैसा क्यों",
    "Atmosphere, light, and the emotional pull of the hills.",
    "சூழல், ஒளி, மலைகளின் உணர்ச்சி ஈர்ப்பு.",
    "माहौल, रोशनी और पहाड़ियों का खिंचाव।",
    ["Culture", "Nature"],
    5,
    "2026-06-16",
    [
      "Kodai’s power is atmosphere. Mist turns ordinary roads into film frames.",
      "You feel it most when you stop chasing and start watching — lake light, pine quiet, valley cloud.",
      "That feeling is why Canaan tells the Kodai story before showing packages.",
    ],
  ],
  [
    "why-kodai-princess-hills",
    "Why they call it Princess of the Hills",
    "ஏன் மலைகளின் இளவரசி என்று அழைக்கிறார்கள்",
    "क्यों कहते हैं पहाड़ियों की रानी",
    "History, climate, and the soft royalty of this hill station.",
    "வரலாறு, காலநிலை, மென்மையான அரச மரியாதை.",
    "इतिहास, जलवायु और इस हिल स्टेशन की कोमल रॉयल्टी।",
    ["Culture", "Guides"],
    5,
    "2026-06-19",
    [
      "The nickname fits: Kodai is elegant rather than harsh — lakes, woods, and a cool temperament.",
      "Colonial-era planning and natural beauty shaped a hill town that still feels graceful.",
      "Visit with curiosity and care, and the title makes sense by the second morning.",
    ],
  ],
  [
    "canaan-kodai-packages-guide",
    "Choosing a Canaan Kodaikanal package",
    "கானான் கொடை பேக்கேஜ் தேர்வு",
    "कनान कोडई पैकेज कैसे चुनें",
    "Escape, Complete, Family, Honeymoon — which rhythm fits you.",
    "Escape, Complete, Family, Honeymoon — உங்களுக்கு ஏற்ற தாளம்.",
    "Escape, Complete, Family, Honeymoon — आपकी लय कौन सी।",
    ["Packages", "Canaan"],
    6,
    "2026-06-22",
    [
      "Kodai Escape suits short resets. Complete suits balanced explorers. Family and Honeymoon follow softer pacing.",
      "Luxury is for travellers who want privacy and quiet more than a long list of stops.",
      "Enquire with dates and traveller type — we match the package to your real rhythm.",
    ],
  ],
];

// Add a few more to clear 55+ with generated extras from place list
const extras = [
  [
    "kodai-evening-walks",
    "Evening walks that feel like Kodai",
    "கொடை போன்ற மாலை நடைகள்",
    "शाम की सैर जो कोडई जैसी लगें",
    "Lake roads, cool air, and why night checklists can wait.",
    "ஏரி சாலைகள், குளிர் காற்று.",
    "झील सड़कें और ठंडी हवा।",
    ["Walks", "Tips"],
    3,
    "2026-06-25",
    [
      "The best Kodai evenings are often the simplest — a slow lake road walk after dinner.",
      "Carry a light jacket and keep phones away from railings in mist.",
      "Let the town noise fade; the hill feeling returns quickly.",
    ],
  ],
  [
    "kodai-rainy-day-plan",
    "A rainy-day plan for Kodaikanal",
    "கொடைக்கானல் மழை நாள் திட்டம்",
    "कोडाइकनाल बरसात के दिन की योजना",
    "Cafés, indoor calm, and short mist windows between showers.",
    "காஃபேக்கள், உட்புற அமைதி.",
    "कैफ़े, इंडोर शांति, बौछारों के बीच कोहरा।",
    ["Tips", "Seasons"],
    4,
    "2026-06-28",
    [
      "Rainy days are for cafés, long breakfasts, and short outings when the mist thins.",
      "Keep one flexible outdoor slot — Kodai often opens a clear hour without warning.",
      "Waterproof shoes matter more than another souvenir.",
    ],
  ],
  [
    "kodai-tea-and-coffee",
    "Tea, coffee, and warm cups in the hills",
    "மலைகளில் தேநீர், காபி, சூடான கப்",
    "पहाड़ियों में चाय-कॉफ़ी की गर्माहट",
    "Where a simple cup becomes part of the landscape.",
    "எளிய கப் எப்படி நிலப்பரப்பின் பகுதியாகிறது.",
    "एक साधारण कप कैसे नज़ारे का हिस्सा बन जाता है।",
    ["Food", "Culture"],
    3,
    "2026-07-01",
    [
      "A warm cup after a mist walk is half the Kodai experience.",
      "Try local cafés away from the loudest strip when you want conversation and quiet.",
      "Build tea stops into itineraries — they pace the day beautifully.",
    ],
  ],
];

const all = [...posts, ...extras];

const lines = [];
lines.push(`export const KODAI_BLOG_IMAGE =`);
lines.push(`  "${IMAGE}";`);
lines.push(``);
lines.push(`export type BlogPost = {`);
lines.push(`  slug: string;`);
lines.push(`  date: string;`);
lines.push(`  readMinutes: number;`);
lines.push(`  image: string;`);
lines.push(`  tags: string[];`);
lines.push(`};`);
lines.push(``);
lines.push(`export type BlogCopy = {`);
lines.push(`  title: Record<"en" | "ta" | "hi", string>;`);
lines.push(`  excerpt: Record<"en" | "ta" | "hi", string>;`);
lines.push(`  body: string[];`);
lines.push(`};`);
lines.push(``);
lines.push(`export const blogPosts: BlogPost[] = [`);

for (const p of all) {
  const [slug, , , , , , , tags, mins, date] = p;
  lines.push(`  {`);
  lines.push(`    slug: "${slug}",`);
  lines.push(`    date: "${date}",`);
  lines.push(`    readMinutes: ${mins},`);
  lines.push(`    image: KODAI_BLOG_IMAGE,`);
  lines.push(`    tags: ${JSON.stringify(tags)},`);
  lines.push(`  },`);
}
lines.push(`];`);
lines.push(``);
lines.push(`export const blogCopy: Record<string, BlogCopy> = {`);

for (const p of all) {
  const [slug, enT, taT, hiT, enE, taE, hiE, , , , body] = p;
  lines.push(`  "${slug}": {`);
  lines.push(`    title: {`);
  lines.push(`      en: ${JSON.stringify(enT)},`);
  lines.push(`      ta: ${JSON.stringify(taT)},`);
  lines.push(`      hi: ${JSON.stringify(hiT)},`);
  lines.push(`    },`);
  lines.push(`    excerpt: {`);
  lines.push(`      en: ${JSON.stringify(enE)},`);
  lines.push(`      ta: ${JSON.stringify(taE)},`);
  lines.push(`      hi: ${JSON.stringify(hiE)},`);
  lines.push(`    },`);
  lines.push(`    body: [`);
  for (const para of body) {
    lines.push(`      ${JSON.stringify(para)},`);
  }
  lines.push(`    ],`);
  lines.push(`  },`);
}
lines.push(`};`);
lines.push(``);
lines.push(`export function getBlogPost(slug: string) {`);
lines.push(`  return blogPosts.find((p) => p.slug === slug);`);
lines.push(`}`);
lines.push(``);
lines.push(`export function getAllBlogSlugs() {`);
lines.push(`  return blogPosts.map((p) => p.slug);`);
lines.push(`}`);
lines.push(``);

const out = join(__dirname, "..", "src", "data", "blog.ts");
writeFileSync(out, lines.join("\n"), "utf8");
console.log(`Wrote ${all.length} posts to ${out}`);
