/**
 * Ebenezer Products — seed catalog (manually curated sample data).
 *
 * IMPORTANT:
 * - Prices are illustrative samples for development / UX.
 * - Replace with approved affiliate feeds or merchant APIs before claiming live accuracy.
 * - Do not scrape marketplaces.
 */

import type {
  CatalogCategory,
  CatalogProduct,
  Merchant,
  Offer,
  ProductVariant,
} from "./types";

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { id: "laptops", name: "Laptops", slug: "laptops", description: "Notebooks for work, study, and creation", parent: "computers" },
  { id: "desktops", name: "Desktops", slug: "desktops", description: "Tower and AIO PCs", parent: "computers" },
  { id: "cpu", name: "CPUs", slug: "cpu", description: "Processors", parent: "components" },
  { id: "gpu", name: "Graphics Cards", slug: "gpu", description: "Discrete GPUs", parent: "components" },
  { id: "ram", name: "RAM", slug: "ram", description: "Memory modules and kits", parent: "components" },
  { id: "ssd", name: "SSDs", slug: "ssd", description: "Solid-state storage", parent: "components" },
  { id: "monitors", name: "Monitors", slug: "monitors", description: "Displays for work and play", parent: "displays" },
  { id: "keyboards", name: "Keyboards", slug: "keyboards", description: "Mechanical and office keyboards", parent: "peripherals" },
  { id: "mice", name: "Mice", slug: "mice", description: "Mice and trackpads", parent: "peripherals" },
  { id: "headphones", name: "Headphones", slug: "headphones", description: "Headsets and earphones", parent: "peripherals" },
  { id: "smartphones", name: "Smartphones", slug: "smartphones", description: "Mobile phones", parent: "mobile" },
  { id: "tablets", name: "Tablets", slug: "tablets", description: "Tablets and iPads", parent: "mobile" },
  { id: "routers", name: "Routers", slug: "routers", description: "Wi-Fi and mesh systems", parent: "networking" },
  { id: "webcams", name: "Webcams", slug: "webcams", description: "USB cameras", parent: "peripherals" },
  { id: "microphones", name: "Microphones", slug: "microphones", description: "USB and XLR mics", parent: "peripherals" },
  { id: "motherboard", name: "Motherboards", slug: "motherboard", description: "PC motherboards", parent: "components" },
];

export const MERCHANTS: Merchant[] = [
  {
    id: "amazon-in",
    name: "Amazon.in",
    website: "https://www.amazon.in",
    country: "IN",
    currency: "INR",
    affiliateNetwork: "amazon_associates",
    status: "active",
  },
  {
    id: "flipkart",
    name: "Flipkart",
    website: "https://www.flipkart.com",
    country: "IN",
    currency: "INR",
    affiliateNetwork: "flipkart_affiliate",
    status: "active",
  },
  {
    id: "mdcomputers",
    name: "MD Computers",
    website: "https://mdcomputers.in",
    country: "IN",
    currency: "INR",
    status: "active",
  },
];

const CHECKED = "2026-08-18T10:00:00.000Z";
const UPDATED = "2026-08-18T10:00:00.000Z";

/** Sample Unsplash hardware imagery — replace with merchant CDN images in production */
const IMG = {
  laptop1: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
  laptop2: "https://images.unsplash.com/photo-1525547719571-a2d4ac882e75?auto=format&fit=crop&w=1200&q=80",
  laptop3: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
  laptop4: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=1200&q=80",
  ssd: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
  ram: "https://images.unsplash.com/photo-1562976540-1502c5aa7c8d?auto=format&fit=crop&w=1200&q=80",
  monitor: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
  gpu: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
};

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "lp-aspire5-ryzen5",
    slug: "acer-aspire-5-ryzen-5-16gb",
    name: "Acer Aspire 5 (Ryzen 5, 16GB)",
    brand: "Acer",
    model: "A515-57",
    categoryId: "laptops",
    shortDescription: "Balanced everyday laptop for coding and light creative work under ₹60,000.",
    description:
      "A practical 15.6\" Windows laptop aimed at students and freelancers. Strong enough for web development, Office, and light Photoshop. Not a high-refresh gaming machine.",
    image: IMG.laptop1,
    specs: {
      cpu: "AMD Ryzen 5 7530U",
      cpu_score: 72,
      gpu: "Radeon Graphics (integrated)",
      gpu_score: 28,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "NVMe SSD",
      display_inches: 15.6,
      display_res: "1920×1080",
      refresh_hz: 60,
      battery_wh: 50,
      weight_kg: 1.8,
      os: "Windows 11",
      warranty_years: 1,
    },
    pros: ["16GB RAM for multitasking", "Decent CPU for coding", "512GB SSD", "Good value under ₹60k"],
    cons: ["Integrated graphics only", "Average display", "Plastic build"],
    bestFor: ["Web development", "College work", "Office + browsing"],
    notIdealFor: ["AAA gaming", "Heavy video editing", "Color-critical design"],
    rating: 4.2,
    reviewCount: 1280,
    status: "active",
    seoTitle: "Acer Aspire 5 Ryzen 5 16GB — Specs, Price Comparison",
    seoDescription: "Compare prices and specs for Acer Aspire 5 with 16GB RAM. Best for coding and study under ₹60,000.",
    updatedAt: UPDATED,
  },
  {
    id: "lp-ideapad-slim3",
    slug: "lenovo-ideapad-slim-3-i5-16gb",
    name: "Lenovo IdeaPad Slim 3 (Core i5, 16GB)",
    brand: "Lenovo",
    model: "Slim 3 15IRH8",
    categoryId: "laptops",
    shortDescription: "Slim Intel i5 laptop with 16GB RAM — solid for coding and Photoshop.",
    description:
      "A thin-and-light style IdeaPad with Intel Core i5 and 16GB RAM. Better portability than bulkier Aspire-class machines. Integrated Iris Xe helps light creative work.",
    image: IMG.laptop2,
    specs: {
      cpu: "Intel Core i5-13420H",
      cpu_score: 78,
      gpu: "Intel Iris Xe",
      gpu_score: 35,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "NVMe SSD",
      display_inches: 15.6,
      display_res: "1920×1080",
      refresh_hz: 60,
      battery_wh: 47,
      weight_kg: 1.62,
      os: "Windows 11",
      warranty_years: 1,
    },
    pros: ["Stronger CPU for multitasking", "Lighter chassis", "Iris Xe for light Photoshop", "Trusted brand support"],
    cons: ["Still not for serious gaming", "Screen is ordinary", "RAM may be soldered on some configs"],
    bestFor: ["Programming", "Photoshop (light)", "Students"],
    notIdealFor: ["Gaming laptops seekers", "4K video editors"],
    rating: 4.3,
    reviewCount: 940,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "lp-loq-4050",
    slug: "lenovo-loq-15-rtx-4050",
    name: "Lenovo LOQ 15 (RTX 4050)",
    brand: "Lenovo",
    model: "LOQ 15IRX9",
    categoryId: "laptops",
    shortDescription: "Gaming + creator laptop with RTX 4050 — better when budget stretches near ₹80–90k.",
    description:
      "Entry gaming notebook with discrete RTX 4050. Suitable when you need occasional gaming plus coding. Heavier and louder than office laptops; battery is weaker.",
    image: IMG.laptop3,
    specs: {
      cpu: "Intel Core i5-13450HX",
      cpu_score: 84,
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      gpu_score: 72,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "NVMe SSD",
      display_inches: 15.6,
      display_res: "1920×1080",
      refresh_hz: 144,
      battery_wh: 60,
      weight_kg: 2.4,
      os: "Windows 11",
      warranty_years: 1,
    },
    pros: ["Real discrete GPU", "144Hz display", "Good for coding + casual gaming", "Upgradeable RAM/SSD on many units"],
    cons: ["Heavier", "Shorter battery life", "Fans can be loud", "Price higher than office laptops"],
    bestFor: ["Coding + occasional gaming", "Light 3D", "Students who game"],
    notIdealFor: ["Ultra-portable travel", "All-day battery users"],
    rating: 4.4,
    reviewCount: 2100,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "lp-victus-3050",
    slug: "hp-victus-15-rtx-3050",
    name: "HP Victus 15 (RTX 3050)",
    brand: "HP",
    model: "15-fa1351TX",
    categoryId: "laptops",
    shortDescription: "Budget gaming laptop — useful when you need a GPU but stay closer to ₹65–75k.",
    description:
      "Victus brings an RTX 3050 into a more reachable price band. Fine for esports and older titles; not as strong as 4050 class for modern AAA or GPU-heavy creative apps.",
    image: IMG.laptop4,
    specs: {
      cpu: "Intel Core i5-12500H",
      cpu_score: 76,
      gpu: "NVIDIA GeForce RTX 3050 4GB",
      gpu_score: 55,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "NVMe SSD",
      display_inches: 15.6,
      display_res: "1920×1080",
      refresh_hz: 144,
      battery_wh: 70,
      weight_kg: 2.29,
      os: "Windows 11",
      warranty_years: 1,
    },
    pros: ["Discrete GPU at lower price", "144Hz panel", "16GB RAM", "Known service network"],
    cons: ["Older GPU generation", "Build is average", "Thermals under load"],
    bestFor: ["Budget gaming", "Coding + light games"],
    notIdealFor: ["Ray-traced AAA gaming", "Thin-and-light preference"],
    rating: 4.1,
    reviewCount: 3200,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "lp-macbook-air-m2",
    slug: "apple-macbook-air-m2-8gb",
    name: "Apple MacBook Air M2 (8GB)",
    brand: "Apple",
    model: "MacBook Air 13 M2",
    categoryId: "laptops",
    shortDescription: "Premium ultralight — excellent battery and build; 8GB base is tight for heavy multitasking.",
    description:
      "MacBook Air M2 is excellent for writing, coding (web), and media consumption. The 8GB base config can struggle with many Chrome tabs + Docker + design tools at once. Consider 16GB if budget allows.",
    image: IMG.laptop2,
    specs: {
      cpu: "Apple M2",
      cpu_score: 88,
      gpu: "Apple M2 8-core GPU",
      gpu_score: 48,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      display_inches: 13.6,
      display_res: "2560×1664",
      refresh_hz: 60,
      battery_wh: 52.6,
      weight_kg: 1.24,
      os: "macOS",
      warranty_years: 1,
    },
    pros: ["Excellent battery", "Brilliant display", "Silent and cool", "Premium build"],
    cons: ["8GB RAM limits heavy multitasking", "256GB storage fills fast", "Higher price", "Not for Windows-only software"],
    bestFor: ["Writing", "Web development (lightweight stacks)", "Travel"],
    notIdealFor: ["Windows-only workflows", "Heavy gaming", "Large local media libraries"],
    rating: 4.7,
    reviewCount: 8900,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "ssd-wd-sn770-1tb",
    slug: "wd-black-sn770-1tb",
    name: "WD Black SN770 1TB NVMe",
    brand: "WD",
    model: "SN770 1TB",
    categoryId: "ssd",
    shortDescription: "Fast PCIe Gen4 NVMe SSD — strong upgrade for gaming PCs and laptops with M.2 slots.",
    description: "Dramless Gen4 drive popular for capacity upgrades. Check laptop M.2 length and heatsink clearance before buying.",
    image: IMG.ssd,
    specs: {
      capacity_gb: 1000,
      interface: "NVMe PCIe Gen4",
      form_factor: "M.2 2280",
      read_mbps: 5150,
      write_mbps: 4900,
      warranty_years: 5,
      storage_score: 82,
    },
    pros: ["1TB capacity", "Fast Gen4 speeds", "Good price/performance", "5-year warranty"],
    cons: ["Dramless design", "Needs Gen4 slot for full speed"],
    bestFor: ["Gaming PC upgrades", "Laptop storage upgrades"],
    notIdealFor: ["SATA-only laptops", "Enterprise write-heavy servers"],
    rating: 4.6,
    reviewCount: 4500,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "ram-corsair-32-ddr4",
    slug: "corsair-vengeance-32gb-ddr4-3200",
    name: "Corsair Vengeance 32GB (2×16) DDR4-3200",
    brand: "Corsair",
    model: "CMK32GX4M2E3200C16",
    categoryId: "ram",
    shortDescription: "Desktop DDR4 kit for multitasking, video editing, and gaming PCs.",
    description: "Common desktop upgrade kit. Confirm motherboard DDR generation (DDR4 vs DDR5) before purchase.",
    image: IMG.ram,
    specs: {
      capacity_gb: 32,
      ddr_gen: "DDR4",
      speed_mt: 3200,
      form_factor: "DIMM",
      kit: "2x16GB",
      ecc: false,
      ram_score: 80,
    },
    pros: ["32GB for heavy multitasking", "Widely compatible DDR4", "Trusted brand"],
    cons: ["Not for DDR5 boards", "Not SODIMM for most laptops"],
    bestFor: ["Desktop upgrades", "Editing PCs"],
    notIdealFor: ["Laptop SODIMM needs", "DDR5 platforms"],
    rating: 4.7,
    reviewCount: 6100,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "mon-lg-27ul650",
    slug: "lg-27-4k-ips-monitor",
    name: "LG 27\" 4K IPS Monitor",
    brand: "LG",
    model: "27UL650-W",
    categoryId: "monitors",
    shortDescription: "4K IPS monitor for coding real-estate and photo work.",
    description: "Sharp 4K panel useful for programming (more windows) and photo editing. Verify stand height and ports for your desk setup.",
    image: IMG.monitor,
    specs: {
      size_inches: 27,
      resolution: "3840×2160",
      panel: "IPS",
      refresh_hz: 60,
      ports: "HDMI, DisplayPort, USB-C",
      display_score: 85,
      warranty_years: 3,
    },
    pros: ["4K clarity", "IPS colors", "Good for coding + photos"],
    cons: ["60Hz only", "Needs strong GPU for 4K gaming"],
    bestFor: ["Programming", "Photo editing", "Office productivity"],
    notIdealFor: ["Competitive esports (high Hz)"],
    rating: 4.5,
    reviewCount: 1800,
    status: "active",
    updatedAt: UPDATED,
  },
  {
    id: "gpu-rtx4060",
    slug: "nvidia-rtx-4060-8gb",
    name: "NVIDIA GeForce RTX 4060 8GB",
    brand: "NVIDIA",
    model: "RTX 4060",
    categoryId: "gpu",
    shortDescription: "Efficient 1080p/1440p gaming GPU for mid-range desktops.",
    description: "Popular mid-range card. Partner board prices vary — compare offers carefully and check PSU connectors.",
    image: IMG.gpu,
    specs: {
      vram_gb: 8,
      gpu_arch: "Ada Lovelace",
      gpu_score: 74,
      power_w: 115,
      ports: "HDMI, DisplayPort",
      warranty_years: 3,
    },
    pros: ["Efficient power use", "DLSS 3", "Good 1080p/1440p gaming"],
    cons: ["8GB VRAM can limit some titles", "Partner card prices vary a lot"],
    bestFor: ["1080p/1440p gaming PCs", "Light creative acceleration"],
    notIdealFor: ["4K ultra gaming on a budget"],
    rating: 4.4,
    reviewCount: 5200,
    status: "active",
    updatedAt: UPDATED,
  },
];

export const PRODUCT_VARIANTS: ProductVariant[] = [
  {
    id: "lp-aspire5-ryzen5-var-default",
    productId: "lp-aspire5-ryzen5",
    name: "16GB / 512GB",
    specs: { ram_gb: 16, storage_gb: 512 },
  },
  {
    id: "lp-macbook-air-m2-var-8-256",
    productId: "lp-macbook-air-m2",
    name: "8GB / 256GB",
    specs: { ram_gb: 8, storage_gb: 256 },
  },
];

/** Sample offers — prices are DEMO only until affiliate feeds are connected */
export const OFFERS: Offer[] = [
  {
    id: "off-aspire-amz",
    productId: "lp-aspire5-ryzen5",
    merchantId: "amazon-in",
    price: 54990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=Acer+Aspire+5+Ryzen+5+16GB",
    shippingNote: "Prime shipping where available",
    warranty: "1 year manufacturer",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-aspire-fk",
    productId: "lp-aspire5-ryzen5",
    merchantId: "flipkart",
    price: 55990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.flipkart.com/search?q=acer%20aspire%205%20ryzen%205",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-ideapad-amz",
    productId: "lp-ideapad-slim3",
    merchantId: "amazon-in",
    price: 58990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=Lenovo+IdeaPad+Slim+3+i5+16GB",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-ideapad-fk",
    productId: "lp-ideapad-slim3",
    merchantId: "flipkart",
    price: 57990,
    currency: "INR",
    availability: "limited",
    url: "https://www.flipkart.com/search?q=ideapad%20slim%203%20i5%2016gb",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-loq-amz",
    productId: "lp-loq-4050",
    merchantId: "amazon-in",
    price: 84990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=Lenovo+LOQ+RTX+4050",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-victus-amz",
    productId: "lp-victus-3050",
    merchantId: "amazon-in",
    price: 69990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=HP+Victus+15+RTX+3050",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-victus-fk",
    productId: "lp-victus-3050",
    merchantId: "flipkart",
    price: 68490,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.flipkart.com/search?q=hp%20victus%2015%20rtx%203050",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-mba-amz",
    productId: "lp-macbook-air-m2",
    merchantId: "amazon-in",
    price: 84990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=MacBook+Air+M2+8GB",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-ssd-amz",
    productId: "ssd-wd-sn770-1tb",
    merchantId: "amazon-in",
    price: 6499,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=WD+Black+SN770+1TB",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-ssd-md",
    productId: "ssd-wd-sn770-1tb",
    merchantId: "mdcomputers",
    price: 6299,
    currency: "INR",
    availability: "in_stock",
    url: "https://mdcomputers.in/",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "low",
  },
  {
    id: "off-ram-amz",
    productId: "ram-corsair-32-ddr4",
    merchantId: "amazon-in",
    price: 7499,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=Corsair+Vengeance+32GB+DDR4+3200",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-mon-amz",
    productId: "mon-lg-27ul650",
    merchantId: "amazon-in",
    price: 28990,
    currency: "INR",
    availability: "unknown",
    url: "https://www.amazon.in/s?k=LG+27+4K+IPS+monitor",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "low",
  },
  {
    id: "off-gpu-amz",
    productId: "gpu-rtx4060",
    merchantId: "amazon-in",
    price: 29990,
    currency: "INR",
    availability: "in_stock",
    url: "https://www.amazon.in/s?k=RTX+4060+8GB",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
  {
    id: "off-gpu-md",
    productId: "gpu-rtx4060",
    merchantId: "mdcomputers",
    price: 28990,
    currency: "INR",
    availability: "in_stock",
    url: "https://mdcomputers.in/",
    lastCheckedAt: CHECKED,
    source: "manual",
    confidence: "medium",
  },
];

export function getCategory(id: string) {
  return CATALOG_CATEGORIES.find((c) => c.id === id || c.slug === id);
}

export function getProductBySlug(slug: string) {
  return CATALOG_PRODUCTS.find((p) => p.slug === slug && p.status === "active");
}

export function getProductById(id: string) {
  return CATALOG_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(categoryId: string) {
  return CATALOG_PRODUCTS.filter((p) => p.categoryId === categoryId && p.status === "active");
}

export function getOffersForProduct(productId: string) {
  return OFFERS.filter((o) => o.productId === productId).sort((a, b) => a.price - b.price);
}

export function getBestOffer(productId: string) {
  const offers = getOffersForProduct(productId).filter((o) => o.availability !== "out_of_stock");
  return offers[0] ?? null;
}

export function getMerchant(id: string) {
  return MERCHANTS.find((m) => m.id === id);
}

export function formatINR(amount: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function isOfferStale(offer: Offer, maxAgeHours = 72) {
  const age = Date.now() - new Date(offer.lastCheckedAt).getTime();
  return age > maxAgeHours * 60 * 60 * 1000;
}
