import type { NetworkToolCategory, NetworkToolMeta } from "./types";
import { CATEGORY_LABELS } from "./types";

const D = "2026-08-24T00:00:00.000Z";

function tool(
  partial: Omit<NetworkToolMeta, "createdAt" | "updatedAt" | "status"> & {
    status?: NetworkToolMeta["status"];
  }
): NetworkToolMeta {
  return {
    createdAt: D,
    updatedAt: D,
    status: "live",
    ...partial,
  };
}

/** Only live tools are registered here — every entry must have a working UI. */
export const NETWORK_TOOLS: NetworkToolMeta[] = [
  tool({
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Format, validate, minify and beautify JSON instantly in your browser.",
    category: "developer",
    icon: "Braces",
    keywords: ["json", "format", "beautify", "validate", "minify", "pretty"],
    synonyms: ["pretty print json", "json beautifier"],
    seoTitle: "JSON Formatter — Format & Validate JSON Online",
    seoDescription:
      "Free JSON formatter and validator. Beautify, minify, and copy JSON safely in your browser — no upload required.",
    featured: true,
    related: ["json-validator", "base64-encoder", "url-encoder"],
    howItWorks: [
      "Paste or type JSON in the input panel.",
      "Click Format to beautify, or Validate to check syntax.",
      "Copy or download the result — processing stays on your device.",
    ],
    features: ["Format & minify", "Syntax validation", "Copy / download", "Runs locally in the browser"],
    faqs: [
      {
        q: "Is my JSON uploaded to a server?",
        a: "No. Formatting and validation run entirely in your browser.",
      },
      {
        q: "Does it support large files?",
        a: "It works well for typical API payloads. Extremely large documents may be limited by browser memory.",
      },
    ],
    example: '{\n  "hello": "world",\n  "ok": true\n}',
  }),
  tool({
    id: "json-validator",
    name: "JSON Validator",
    slug: "json-validator",
    description: "Check whether a JSON string is valid and see clear error messages.",
    category: "developer",
    icon: "ShieldCheck",
    keywords: ["json", "validate", "syntax", "error"],
    seoTitle: "JSON Validator — Check JSON Syntax Online",
    seoDescription: "Validate JSON instantly and see precise parse errors. Free, private, browser-based.",
    featured: true,
    related: ["json-formatter", "jwt-decoder"],
    howItWorks: ["Paste JSON", "Click Validate", "Read the success or error message"],
    features: ["Clear error text", "Line-friendly feedback", "Private — local only"],
    faqs: [
      { q: "Does valid JSON mean my API is correct?", a: "No — it only checks JSON syntax, not your business rules." },
    ],
  }),
  tool({
    id: "base64-encoder",
    name: "Base64 Encoder / Decoder",
    slug: "base64-encoder",
    description: "Encode text to Base64 or decode Base64 back to text.",
    category: "developer",
    icon: "Binary",
    keywords: ["base64", "encode", "decode"],
    seoTitle: "Base64 Encoder Decoder Online",
    seoDescription: "Free Base64 encode and decode tool. Works in your browser with Unicode-safe handling.",
    featured: true,
    related: ["url-encoder", "hash-generator", "jwt-decoder"],
    howItWorks: ["Enter text or Base64", "Choose Encode or Decode", "Copy the result"],
    features: ["Encode & decode", "Unicode-safe", "One-click copy"],
    faqs: [{ q: "Is Base64 encryption?", a: "No. Base64 is encoding, not encryption. Anyone can decode it." }],
  }),
  tool({
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    slug: "url-encoder",
    description: "Encode or decode URL query strings and path segments safely.",
    category: "developer",
    icon: "Link",
    keywords: ["url", "encode", "decode", "percent", "uri"],
    seoTitle: "URL Encoder Decoder Online",
    seoDescription: "Encode and decode URLs and query parameters instantly. Free developer utility.",
    related: ["base64-encoder", "slug-generator"],
    howItWorks: ["Paste a URL or string", "Encode or Decode", "Copy the output"],
    features: ["encodeURIComponent style", "Decode support", "Copy button"],
    faqs: [{ q: "When should I encode?", a: "When putting user text into query parameters or path segments." }],
  }),
  tool({
    id: "uuid-generator",
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate UUID v4 identifiers for apps, databases, and APIs.",
    category: "developer",
    icon: "Fingerprint",
    keywords: ["uuid", "guid", "v4", "id"],
    seoTitle: "UUID Generator — Free UUID v4 Online",
    seoDescription: "Generate secure UUID v4 values instantly in your browser.",
    featured: true,
    related: ["hash-generator", "timestamp-converter"],
    howItWorks: ["Choose how many UUIDs you need", "Click Generate", "Copy one or all"],
    features: ["UUID v4", "Bulk generate", "Copy list"],
    faqs: [{ q: "Are these unique?", a: "UUID v4 values from crypto.randomUUID() are suitable for most app IDs." }],
  }),
  tool({
    id: "jwt-decoder",
    name: "JWT Decoder",
    slug: "jwt-decoder",
    description: "Decode JWT header and payload locally. Does not verify signatures.",
    category: "developer",
    icon: "KeyRound",
    keywords: ["jwt", "token", "decode", "payload"],
    seoTitle: "JWT Decoder Online — Inspect Tokens Locally",
    seoDescription: "Decode JWT header and payload in your browser. Signature verification is not performed.",
    related: ["base64-encoder", "json-formatter"],
    howItWorks: ["Paste a JWT", "View decoded header and payload", "Copy JSON if needed"],
    features: ["Header + payload view", "Local only", "No signature verify (by design)"],
    faqs: [
      {
        q: "Does this verify the token?",
        a: "No. It only decodes. Never trust a JWT without proper signature verification on a server.",
      },
    ],
  }),
  tool({
    id: "regex-tester",
    name: "Regex Tester",
    slug: "regex-tester",
    description: "Test regular expressions against sample text with live match highlights.",
    category: "developer",
    icon: "Regex",
    keywords: ["regex", "regexp", "pattern", "match"],
    seoTitle: "Regex Tester Online",
    seoDescription: "Test JavaScript regular expressions with live matches. Free and private.",
    related: ["json-formatter", "text-cleaner"],
    howItWorks: ["Enter a pattern and flags", "Paste test text", "See matches instantly"],
    features: ["Live matches", "Flags support", "Error messages"],
    faqs: [{ q: "Which regex flavor?", a: "JavaScript RegExp, as used in modern browsers." }],
  }),
  tool({
    id: "hash-generator",
    name: "Hash Generator",
    slug: "hash-generator",
    description: "Generate SHA-256, SHA-384, or SHA-512 hashes from text in the browser.",
    category: "developer",
    icon: "Hash",
    keywords: ["hash", "sha256", "sha512", "checksum"],
    seoTitle: "Hash Generator — SHA-256 Online",
    seoDescription: "Create SHA hashes from text using the Web Crypto API. Nothing leaves your browser.",
    related: ["uuid-generator", "base64-encoder"],
    howItWorks: ["Enter text", "Choose algorithm", "Copy the hex digest"],
    features: ["SHA-256 / 384 / 512", "Hex output", "Local crypto"],
    faqs: [{ q: "Is hashing encryption?", a: "No. Hashes are one-way digests, not reversible encryption." }],
  }),
  tool({
    id: "timestamp-converter",
    name: "Timestamp Converter",
    slug: "timestamp-converter",
    description: "Convert Unix timestamps to human dates and back.",
    category: "developer",
    icon: "Clock",
    keywords: ["timestamp", "unix", "epoch", "date"],
    seoTitle: "Unix Timestamp Converter Online",
    seoDescription: "Convert between Unix epoch seconds/milliseconds and readable dates.",
    related: ["uuid-generator"],
    howItWorks: ["Paste a timestamp or pick now", "Convert either direction", "Copy ISO or locale string"],
    features: ["Seconds & ms", "ISO output", "Now button"],
    faqs: [{ q: "Seconds or milliseconds?", a: "Values ≥ 1e12 are treated as milliseconds." }],
  }),
  tool({
    id: "color-converter",
    name: "Color Converter",
    slug: "color-converter",
    description: "Convert between HEX, RGB, and HSL color formats.",
    category: "developer",
    icon: "Palette",
    keywords: ["color", "hex", "rgb", "hsl"],
    seoTitle: "Color Converter — HEX RGB HSL",
    seoDescription: "Convert colors between HEX, RGB, and HSL with a live preview.",
    related: ["css-formatter"],
    howItWorks: ["Enter a color in any supported format", "See conversions update", "Copy the value you need"],
    features: ["HEX / RGB / HSL", "Live swatch", "Copy buttons"],
    faqs: [{ q: "Alpha support?", a: "This tool focuses on opaque colors (no alpha channel)." }],
  }),
  tool({
    id: "markdown-preview",
    name: "Markdown Preview",
    slug: "markdown-preview",
    description: "Write Markdown and preview rendered HTML side by side.",
    category: "developer",
    icon: "FileText",
    keywords: ["markdown", "md", "preview", "readme"],
    seoTitle: "Markdown Preview Online",
    seoDescription: "Live Markdown editor and preview. Free, private, browser-based.",
    featured: true,
    related: ["word-counter", "slug-generator"],
    howItWorks: ["Type Markdown on the left", "Preview on the right", "Copy Markdown when ready"],
    features: ["Live preview", "GFM-friendly subset", "Copy source"],
    faqs: [{ q: "Is HTML allowed?", a: "Raw HTML may be limited for safety in the preview." }],
  }),
  tool({
    id: "html-formatter",
    name: "HTML Formatter",
    slug: "html-formatter",
    description: "Beautify HTML indentation for readability.",
    category: "developer",
    icon: "Code2",
    keywords: ["html", "format", "beautify", "indent"],
    seoTitle: "HTML Formatter Online",
    seoDescription: "Indent and beautify HTML markup in your browser.",
    related: ["css-formatter", "javascript-formatter"],
    howItWorks: ["Paste HTML", "Click Format", "Copy the indented result"],
    features: ["Indentation", "Copy output", "Local processing"],
    faqs: [{ q: "Does it validate HTML5?", a: "It formats structure for reading — it is not a full W3C validator." }],
  }),
  tool({
    id: "css-formatter",
    name: "CSS Formatter",
    slug: "css-formatter",
    description: "Beautify or minify CSS for development and delivery.",
    category: "developer",
    icon: "Paintbrush",
    keywords: ["css", "format", "minify", "beautify"],
    seoTitle: "CSS Formatter & Minifier Online",
    seoDescription: "Format or minify CSS instantly in your browser.",
    related: ["html-formatter", "javascript-formatter"],
    howItWorks: ["Paste CSS", "Format or Minify", "Copy the result"],
    features: ["Beautify", "Minify", "Copy"],
    faqs: [{ q: "Does it understand SCSS?", a: "It targets standard CSS. Nested SCSS may need a dedicated compiler." }],
  }),
  tool({
    id: "javascript-formatter",
    name: "JavaScript Formatter",
    slug: "javascript-formatter",
    description: "Indent JavaScript for readability (best-effort beautify).",
    category: "developer",
    icon: "FileCode",
    keywords: ["javascript", "js", "format", "beautify"],
    seoTitle: "JavaScript Formatter Online",
    seoDescription: "Beautify JavaScript indentation in your browser.",
    related: ["json-formatter", "html-formatter"],
    howItWorks: ["Paste JS", "Click Format", "Copy indented code"],
    features: ["Indentation", "Copy", "Local only"],
    faqs: [
      {
        q: "Is this Prettier?",
        a: "No. It is a lightweight indenter for quick readability — not a full AST formatter.",
      },
    ],
  }),
  tool({
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Generate title, description, and social meta tags for your pages.",
    category: "seo",
    icon: "Tags",
    keywords: ["meta", "seo", "title", "description", "og"],
    synonyms: ["meta tags", "seo tags"],
    seoTitle: "Meta Tag Generator — SEO & Open Graph",
    seoDescription: "Create title, description, and Open Graph meta tags for better SEO and sharing.",
    featured: true,
    related: ["open-graph-generator", "robots-txt-generator", "slug-generator"],
    howItWorks: ["Fill in title, description, URL, image", "Copy the generated tags", "Paste into your HTML head"],
    features: ["Title & description", "Open Graph basics", "Copy HTML"],
    faqs: [{ q: "Do meta tags guarantee rankings?", a: "No — they help clarity and sharing; rankings need quality content too." }],
  }),
  tool({
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    slug: "robots-txt-generator",
    description: "Build a robots.txt file with allow/disallow rules and sitemap URL.",
    category: "seo",
    icon: "Bot",
    keywords: ["robots", "robots.txt", "crawler", "seo"],
    seoTitle: "Robots.txt Generator Online",
    seoDescription: "Create a robots.txt file with common crawl rules and sitemap reference.",
    featured: true,
    related: ["sitemap-generator", "meta-tag-generator"],
    howItWorks: ["Choose allow/disallow paths", "Add sitemap URL", "Copy or download robots.txt"],
    features: ["User-agent rules", "Sitemap line", "Download"],
    faqs: [{ q: "Where do I put robots.txt?", a: "At your site root: https://example.com/robots.txt" }],
  }),
  tool({
    id: "sitemap-generator",
    name: "Sitemap Generator",
    slug: "sitemap-generator",
    description: "Generate a basic XML sitemap from a list of URLs.",
    category: "seo",
    icon: "Map",
    keywords: ["sitemap", "xml", "seo", "urls"],
    seoTitle: "XML Sitemap Generator Online",
    seoDescription: "Turn a list of URLs into a basic XML sitemap for search engines.",
    related: ["robots-txt-generator", "slug-generator"],
    howItWorks: ["Paste one URL per line", "Generate XML", "Download sitemap.xml"],
    features: ["URL list → XML", "Download", "Basic lastmod"],
    faqs: [
      {
        q: "Is this enough for huge sites?",
        a: "For large sites, use automated sitemap generation from your CMS or framework.",
      },
    ],
  }),
  tool({
    id: "slug-generator",
    name: "Slug Generator",
    slug: "slug-generator",
    description: "Convert titles into clean URL slugs.",
    category: "seo",
    icon: "Wand2",
    keywords: ["slug", "url", "permalink", "kebab"],
    seoTitle: "URL Slug Generator Online",
    seoDescription: "Create SEO-friendly URL slugs from any title or phrase.",
    related: ["meta-tag-generator", "word-counter"],
    howItWorks: ["Type a title", "See the slug update", "Copy it"],
    features: ["Kebab-case", "Strip punctuation", "Copy"],
    faqs: [{ q: "Unicode titles?", a: "Non-Latin characters are removed or simplified for broad URL compatibility." }],
  }),
  tool({
    id: "open-graph-generator",
    name: "Open Graph Generator",
    slug: "open-graph-generator",
    description: "Generate Open Graph tags for social link previews.",
    category: "seo",
    icon: "Share2",
    keywords: ["open graph", "og", "facebook", "social"],
    seoTitle: "Open Graph Tag Generator",
    seoDescription: "Create Open Graph meta tags for richer social previews.",
    related: ["meta-tag-generator", "canonical-url-generator"],
    howItWorks: ["Enter title, description, URL, image", "Copy OG tags", "Add to your page head"],
    features: ["og:title/description/url/image", "Copy HTML"],
    faqs: [{ q: "Will previews update instantly?", a: "Social networks cache previews — you may need their debugger tools." }],
  }),
  tool({
    id: "canonical-url-generator",
    name: "Canonical URL Generator",
    slug: "canonical-url-generator",
    description: "Generate a canonical link tag for duplicate URL control.",
    category: "seo",
    icon: "Link2",
    keywords: ["canonical", "seo", "duplicate"],
    seoTitle: "Canonical URL Tag Generator",
    seoDescription: "Create a rel=canonical link tag to point search engines at your preferred URL.",
    related: ["meta-tag-generator", "slug-generator"],
    howItWorks: ["Enter the preferred absolute URL", "Copy the link tag", "Place it in <head>"],
    features: ["Absolute URL check", "Copy tag"],
    faqs: [{ q: "Relative URLs?", a: "Prefer absolute https URLs for canonical tags." }],
  }),
  tool({
    id: "keyword-density",
    name: "Keyword Density Checker",
    slug: "keyword-density",
    description: "Analyze word frequency in a passage of text.",
    category: "seo",
    icon: "BarChart3",
    keywords: ["keyword", "density", "seo", "frequency"],
    seoTitle: "Keyword Density Checker Online",
    seoDescription: "Check word frequency and density in your content. Free SEO helper.",
    related: ["word-counter", "slug-generator"],
    howItWorks: ["Paste your content", "See top words and counts", "Use density as a guide — not a rigid rule"],
    features: ["Top terms", "Counts & %", "Stop-word filter"],
    faqs: [
      {
        q: "Is higher density better?",
        a: "No. Write for humans. Density is a diagnostic, not a ranking guarantee.",
      },
    ],
  }),
  tool({
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, sentences, and reading time.",
    category: "text",
    icon: "WholeWord",
    keywords: ["word count", "characters", "reading time"],
    seoTitle: "Word Counter — Characters & Reading Time",
    seoDescription: "Count words and characters instantly. Estimate reading time for your draft.",
    featured: true,
    related: ["case-converter", "text-cleaner", "keyword-density"],
    howItWorks: ["Paste text", "See live counts", "Use reading time as an estimate"],
    features: ["Words / chars", "Sentences", "Reading time"],
    faqs: [{ q: "How is reading time calculated?", a: "About 200 words per minute — an estimate only." }],
  }),
  tool({
    id: "case-converter",
    name: "Case Converter",
    slug: "case-converter",
    description: "Convert text to upper, lower, title, or sentence case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["uppercase", "lowercase", "title case"],
    seoTitle: "Case Converter Online",
    seoDescription: "Switch text between UPPER, lower, Title Case, and more.",
    related: ["word-counter", "slug-generator"],
    howItWorks: ["Paste text", "Pick a case", "Copy the result"],
    features: ["Multiple cases", "Copy", "Instant"],
    faqs: [{ q: "Title case rules?", a: "Uses a simple word-capitalization approach — not Chicago Manual perfection." }],
  }),
  tool({
    id: "text-cleaner",
    name: "Text Cleaner",
    slug: "text-cleaner",
    description: "Remove extra spaces, blank lines, and tidy pasted text.",
    category: "text",
    icon: "Eraser",
    keywords: ["clean text", "trim", "whitespace"],
    seoTitle: "Text Cleaner — Remove Extra Spaces",
    seoDescription: "Clean messy pasted text: trim spaces, collapse blanks, normalize lines.",
    related: ["duplicate-line-remover", "word-counter"],
    howItWorks: ["Paste messy text", "Choose clean options", "Copy the cleaned output"],
    features: ["Trim", "Collapse spaces", "Remove blank lines"],
    faqs: [{ q: "Does it change meaning?", a: "It only adjusts whitespace and blank lines — not wording." }],
  }),
  tool({
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum",
    description: "Generate placeholder paragraphs for layouts and mockups.",
    category: "text",
    icon: "AlignLeft",
    keywords: ["lorem", "ipsum", "placeholder", "dummy text"],
    seoTitle: "Lorem Ipsum Generator Online",
    seoDescription: "Generate classic placeholder text for design mockups.",
    related: ["word-counter", "markdown-preview"],
    howItWorks: ["Choose paragraph count", "Generate", "Copy"],
    features: ["Multiple paragraphs", "Copy"],
    faqs: [{ q: "Should I publish lorem ipsum?", a: "No — use it only for design placeholders." }],
  }),
  tool({
    id: "duplicate-line-remover",
    name: "Duplicate Line Remover",
    slug: "duplicate-line-remover",
    description: "Remove duplicate lines from a list while keeping order.",
    category: "text",
    icon: "ListFilter",
    keywords: ["unique lines", "dedupe", "duplicates"],
    seoTitle: "Remove Duplicate Lines Online",
    seoDescription: "Deduplicate lines in a list while preserving first-seen order.",
    related: ["text-cleaner", "word-counter"],
    howItWorks: ["Paste one item per line", "Remove duplicates", "Copy unique list"],
    features: ["Order preserved", "Case-sensitive option", "Copy"],
    faqs: [{ q: "Case sensitive?", a: "You can choose whether Hello and hello count as the same line." }],
  }),
  tool({
    id: "percentage-calculator",
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Calculate percentages, increases, decreases, and “X is what % of Y”.",
    category: "calculators",
    icon: "Percent",
    keywords: ["percentage", "percent", "increase", "discount math"],
    seoTitle: "Percentage Calculator Online",
    seoDescription: "Free percentage calculator for everyday math, discounts, and growth.",
    featured: true,
    related: ["discount-calculator", "gst-calculator"],
    howItWorks: ["Pick a calculation mode", "Enter numbers", "Read the result"],
    features: ["Multiple modes", "Clear results", "Instant"],
    faqs: [{ q: "Rounding?", a: "Results show sensible decimal precision for readability." }],
  }),
  tool({
    id: "gst-calculator",
    name: "GST Calculator",
    slug: "gst-calculator",
    description: "Calculate GST-inclusive and exclusive amounts for India rates.",
    category: "calculators",
    icon: "Receipt",
    keywords: ["gst", "tax", "india", "cgst", "sgst"],
    synonyms: ["calculate tax", "india gst"],
    seoTitle: "GST Calculator India — Inclusive & Exclusive",
    seoDescription: "Calculate GST amount, CGST/SGST split, and totals for common Indian rates.",
    featured: true,
    related: ["percentage-calculator", "profit-margin-calculator", "invoice-calculator"],
    howItWorks: ["Enter amount and GST %", "Choose inclusive or exclusive", "See tax and total breakdown"],
    features: ["5/12/18/28% presets", "CGST/SGST split", "Inclusive mode"],
    faqs: [
      {
        q: "Is this tax advice?",
        a: "No. It is a math helper. Confirm rates and rules with a tax professional.",
      },
    ],
  }),
  tool({
    id: "emi-calculator",
    name: "EMI Calculator",
    slug: "emi-calculator",
    description: "Estimate loan EMI from principal, interest rate, and tenure.",
    category: "calculators",
    icon: "Landmark",
    keywords: ["emi", "loan", "interest", "mortgage"],
    seoTitle: "EMI Calculator — Loan Payment Estimator",
    seoDescription: "Estimate monthly EMI for personal, home, or vehicle loans.",
    related: ["loan-calculator", "percentage-calculator"],
    howItWorks: ["Enter principal, annual rate, months", "See EMI and total interest", "Adjust tenure to compare"],
    features: ["Monthly EMI", "Total interest", "Total payment"],
    faqs: [{ q: "Exact bank EMI?", a: "Banks may use different day-count or fee rules — treat this as an estimate." }],
  }),
  tool({
    id: "discount-calculator",
    name: "Discount Calculator",
    slug: "discount-calculator",
    description: "Find sale price and savings from original price and discount %.",
    category: "calculators",
    icon: "BadgePercent",
    keywords: ["discount", "sale", "off", "savings"],
    seoTitle: "Discount Calculator Online",
    seoDescription: "Calculate discounted price and how much you save.",
    related: ["percentage-calculator", "profit-margin-calculator"],
    howItWorks: ["Enter original price and discount %", "See final price and savings"],
    features: ["Final price", "Amount saved"],
    faqs: [{ q: "Stacked discounts?", a: "This tool handles a single discount percentage." }],
  }),
  tool({
    id: "age-calculator",
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate exact age in years, months, and days from a birth date.",
    category: "calculators",
    icon: "Cake",
    keywords: ["age", "birthday", "years"],
    seoTitle: "Age Calculator — Years Months Days",
    seoDescription: "Calculate precise age from your date of birth.",
    related: ["time-calculator"],
    howItWorks: ["Pick birth date", "Optionally set “as of” date", "See age breakdown"],
    features: ["Y/M/D breakdown", "As-of date"],
    faqs: [{ q: "Time zones?", a: "Uses your local calendar dates in the browser." }],
  }),
  tool({
    id: "loan-calculator",
    name: "Loan Calculator",
    slug: "loan-calculator",
    description: "Estimate total repayment and interest for a fixed EMI loan.",
    category: "calculators",
    icon: "Wallet",
    keywords: ["loan", "repayment", "interest"],
    seoTitle: "Loan Calculator Online",
    seoDescription: "Estimate total loan repayment and interest using EMI math.",
    related: ["emi-calculator"],
    howItWorks: ["Enter loan details", "Review EMI and totals"],
    features: ["EMI", "Interest total", "Payment total"],
    faqs: [{ q: "Same as EMI tool?", a: "Yes — focused on repayment summary wording for loan shoppers." }],
  }),
  tool({
    id: "time-calculator",
    name: "Time Calculator",
    slug: "time-calculator",
    description: "Add or subtract hours and minutes from a starting time.",
    category: "calculators",
    icon: "Timer",
    keywords: ["time", "hours", "minutes", "duration"],
    seoTitle: "Time Calculator — Add & Subtract Time",
    seoDescription: "Add or subtract hours and minutes quickly.",
    related: ["age-calculator"],
    howItWorks: ["Set a start time", "Add or subtract duration", "See the result"],
    features: ["Add/subtract", "24h friendly"],
    faqs: [{ q: "Overnight?", a: "Results wrap across midnight using a 24-hour clock." }],
  }),
  tool({
    id: "unit-converter",
    name: "Unit Converter",
    slug: "unit-converter",
    description: "Convert length, weight, and temperature units.",
    category: "calculators",
    icon: "Ruler",
    keywords: ["convert", "units", "kg", "km", "celsius"],
    synonyms: ["convert units"],
    seoTitle: "Unit Converter — Length Weight Temperature",
    seoDescription: "Convert common length, weight, and temperature units instantly.",
    related: ["percentage-calculator"],
    howItWorks: ["Choose category", "Enter value", "Read converted units"],
    features: ["Length / weight / temp", "Instant"],
    faqs: [{ q: "Scientific units?", a: "This tool covers everyday conversions, not full SI scientific suites." }],
  }),
  tool({
    id: "invoice-calculator",
    name: "Invoice Calculator",
    slug: "invoice-calculator",
    description: "Add line items, tax, and discounts to estimate an invoice total.",
    category: "business",
    icon: "FileSpreadsheet",
    keywords: ["invoice", "subtotal", "tax", "bill"],
    seoTitle: "Invoice Calculator Online",
    seoDescription: "Estimate invoice totals with line items, discount, and tax.",
    related: ["gst-calculator", "profit-margin-calculator"],
    howItWorks: ["Add item amounts", "Set discount and tax %", "See subtotal and grand total"],
    features: ["Multiple lines", "Discount + tax", "Clear totals"],
    faqs: [{ q: "Does this create PDF invoices?", a: "No — it calculates totals. Use your billing software for documents." }],
  }),
  tool({
    id: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    slug: "profit-margin-calculator",
    description: "Calculate profit, margin %, and markup from cost and selling price.",
    category: "business",
    icon: "TrendingUp",
    keywords: ["margin", "markup", "profit"],
    seoTitle: "Profit Margin Calculator",
    seoDescription: "Find profit, margin percentage, and markup from cost and price.",
    related: ["discount-calculator", "invoice-calculator"],
    howItWorks: ["Enter cost and selling price", "See profit, margin, markup"],
    features: ["Profit", "Margin %", "Markup %"],
    faqs: [{ q: "Margin vs markup?", a: "Margin is profit ÷ price. Markup is profit ÷ cost." }],
  }),
  tool({
    id: "qr-code-generator",
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Create a QR code for a URL or text and download it as PNG.",
    category: "business",
    icon: "QrCode",
    keywords: ["qr", "qr code", "barcode"],
    seoTitle: "QR Code Generator Online",
    seoDescription: "Generate QR codes for links and text. Download as PNG — free and fast.",
    featured: true,
    related: ["slug-generator", "url-encoder"],
    howItWorks: ["Enter text or URL", "Generate QR", "Download PNG"],
    features: ["PNG download", "URL or text", "Client-side render"],
    faqs: [{ q: "Can I scan offline?", a: "Yes — once downloaded, the PNG works like any QR image." }],
  }),
  tool({
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress images in your browser by re-encoding with quality control.",
    category: "image",
    icon: "ImageDown",
    keywords: ["compress image", "reduce size", "jpeg", "webp"],
    synonyms: ["compress a photo", "reduce photo size"],
    seoTitle: "Image Compressor Online — Browser Based",
    seoDescription: "Compress JPG/PNG/WebP images locally in your browser. No server upload.",
    featured: true,
    related: ["image-resizer", "image-converter"],
    howItWorks: ["Choose an image", "Set quality", "Download the compressed file"],
    features: ["Local processing", "Quality slider", "Size comparison"],
    faqs: [
      {
        q: "Is the image uploaded?",
        a: "No. Compression uses the Canvas API in your browser.",
      },
    ],
  }),
  tool({
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize images to exact dimensions or by percentage.",
    category: "image",
    icon: "Scaling",
    keywords: ["resize", "scale", "dimensions"],
    seoTitle: "Image Resizer Online",
    seoDescription: "Resize images in your browser to custom width and height.",
    related: ["image-compressor", "image-converter"],
    howItWorks: ["Upload an image", "Set width/height", "Download resized image"],
    features: ["Lock aspect optional", "PNG/JPEG output", "Local only"],
    faqs: [{ q: "Quality loss?", a: "Resizing and re-encoding can reduce quality — keep originals." }],
  }),
  tool({
    id: "image-converter",
    name: "Image Converter",
    slug: "image-converter",
    description: "Convert images between PNG, JPEG, and WebP in the browser.",
    category: "image",
    icon: "Images",
    keywords: ["convert image", "webp", "png", "jpeg"],
    seoTitle: "Image Converter — PNG JPEG WebP",
    seoDescription: "Convert images between common web formats without uploading to a server.",
    related: ["image-compressor", "image-resizer"],
    howItWorks: ["Upload an image", "Pick output format", "Download"],
    features: ["PNG / JPEG / WebP", "Local convert"],
    faqs: [{ q: "AVIF?", a: "Browser support varies — this tool focuses on PNG, JPEG, and WebP." }],
  }),
  tool({
    id: "ai-prompt-generator",
    name: "AI Prompt Generator",
    slug: "ai-prompt-generator",
    description: "Build clearer prompts for writing, coding, and research tasks.",
    category: "ai",
    icon: "Sparkles",
    keywords: ["prompt", "ai", "chatgpt", "claude"],
    seoTitle: "AI Prompt Generator",
    seoDescription: "Structure better AI prompts with role, goal, constraints, and output format.",
    featured: true,
    related: ["prompt-formatter", "ai-content-outline", "ai-seo-brief"],
    howItWorks: ["Describe your goal", "Add constraints", "Copy the structured prompt into your AI chat"],
    features: ["Structured template", "Copy prompt", "Works offline in-browser"],
    faqs: [
      {
        q: "Does this call an AI model?",
        a: "No. It builds a prompt you can paste into Ebenezer AI or another assistant.",
      },
    ],
  }),
  tool({
    id: "prompt-formatter",
    name: "Prompt Formatter",
    slug: "prompt-formatter",
    description: "Clean and structure a messy prompt into clear sections.",
    category: "ai",
    icon: "ListOrdered",
    keywords: ["format prompt", "ai prompt"],
    seoTitle: "AI Prompt Formatter",
    seoDescription: "Reformat messy prompts into Role / Task / Constraints / Output sections.",
    related: ["ai-prompt-generator", "text-cleaner"],
    howItWorks: ["Paste a rough prompt", "Format into sections", "Copy the improved version"],
    features: ["Sectioned output", "Copy"],
    faqs: [{ q: "Will it invent facts?", a: "No — it only reorganizes the text you provide." }],
  }),
  tool({
    id: "ai-text-helper",
    name: "AI Text Helper",
    slug: "ai-text-helper",
    description: "Prepare rewrite, shorten, or expand instructions for an AI assistant.",
    category: "ai",
    icon: "MessageSquareText",
    keywords: ["rewrite", "shorten", "expand", "ai text"],
    seoTitle: "AI Text Helper — Rewrite Shorten Expand",
    seoDescription: "Turn your draft into a clear instruction for rewriting, shortening, or expanding with AI.",
    related: ["ai-prompt-generator", "word-counter"],
    howItWorks: ["Paste text", "Choose rewrite / shorten / expand", "Copy the instruction + text"],
    features: ["Three modes", "Copy bundle"],
    faqs: [
      {
        q: "Where do I run it?",
        a: "Copy the result into Ebenezer AI (ebenezerdigital.com/ai) or your preferred model.",
      },
    ],
  }),
  tool({
    id: "ai-content-outline",
    name: "AI Content Outline Generator",
    slug: "ai-content-outline",
    description: "Create a blog or guide outline from a topic and audience.",
    category: "ai",
    icon: "ListTree",
    keywords: ["outline", "blog structure", "content plan"],
    seoTitle: "AI Content Outline Generator",
    seoDescription: "Generate a clear article outline template you can refine with AI.",
    related: ["ai-seo-brief", "ai-prompt-generator"],
    howItWorks: ["Enter topic and audience", "Generate outline sections", "Copy into your AI or doc"],
    features: ["H2/H3 style outline", "Audience field"],
    faqs: [{ q: "Is the outline final content?", a: "No — it is a planning scaffold for writing." }],
  }),
  tool({
    id: "ai-seo-brief",
    name: "AI SEO Brief Generator",
    slug: "ai-seo-brief",
    description: "Draft an SEO content brief template for a target keyword.",
    category: "ai",
    icon: "Target",
    keywords: ["seo brief", "content brief", "keyword"],
    seoTitle: "AI SEO Brief Generator",
    seoDescription: "Create a structured SEO brief template for writers and AI assistants.",
    related: ["ai-content-outline", "meta-tag-generator", "keyword-density"],
    howItWorks: ["Enter keyword and intent", "Generate brief sections", "Hand to a writer or AI"],
    features: ["Intent + outline slots", "Copy brief"],
    faqs: [{ q: "Does it fetch SERPs?", a: "No. It builds a brief template from your inputs only." }],
  }),
];

export function getLiveTools(): NetworkToolMeta[] {
  return NETWORK_TOOLS.filter((t) => t.status === "live");
}

export function getToolBySlug(slug: string): NetworkToolMeta | undefined {
  return getLiveTools().find((t) => t.slug === slug);
}

export function getToolsByCategory(category: NetworkToolCategory): NetworkToolMeta[] {
  return getLiveTools().filter((t) => t.category === category);
}

export function getFeaturedTools(limit = 8): NetworkToolMeta[] {
  return getLiveTools().filter((t) => t.featured).slice(0, limit);
}

export function getRelatedTools(slug: string, limit = 4): NetworkToolMeta[] {
  const tool = getToolBySlug(slug);
  if (!tool) return [];
  const related = (tool.related || [])
    .map((s) => getToolBySlug(s))
    .filter(Boolean) as NetworkToolMeta[];
  if (related.length >= limit) return related.slice(0, limit);
  const more = getToolsByCategory(tool.category).filter((t) => t.slug !== slug && !related.some((r) => r.slug === t.slug));
  return [...related, ...more].slice(0, limit);
}

export function categoryLabel(category: NetworkToolCategory): string {
  return CATEGORY_LABELS[category];
}

export { CATEGORY_LABELS };
