import { TOOLS } from "@/app/tools/data";
import { SERVICE_LANDINGS } from "@/lib/services-catalog";
import { STORE_PRODUCTS } from "@/app/products/data";
import { CATALOG_CATEGORIES } from "@/app/catalog/data";
import type { ContentChannel } from "./types";
import { CHANNEL_ARTICLE_TARGET } from "./types";

export const EXPLAINER_ANGLES = [
  "overview",
  "how-to",
  "pricing",
  "alternatives",
  "pros-cons",
  "for-beginners",
  "faq",
] as const;

export const AUDIENCES = [
  "small business owners",
  "freelancers",
  "startups",
  "students",
  "agencies",
  "shop owners",
  "developers",
  "marketers",
  "creators",
  "non-profits",
  "enterprises",
  "remote teams",
  "Indian SMBs",
  "global teams",
  "solo founders",
  "family businesses",
  "retail stores",
  "restaurants",
  "clinics",
  "schools",
  "NGOs",
  "consultants",
  "e-commerce sellers",
  "SaaS founders",
  "designers",
  "writers",
  "accountants",
  "law firms",
  "real estate agents",
  "travel agents",
  "hotels",
  "manufacturers",
  "farmers",
  "coaches",
  "trainers",
  "photographers",
  "YouTubers",
  "podcasters",
  "churches",
  "temples",
  "mosques",
  "community groups",
  "government offices",
  "libraries",
  "hospitals",
  "dental clinics",
  "salons",
  "gyms",
  "gyms and studios",
  "construction firms",
  "logistics companies",
  "warehouses",
  "import-export traders",
  "textile units",
  "jewellery shops",
  "electronics shops",
  "mobile repair shops",
  "computer shops",
  "printing presses",
  "publishers",
  "event planners",
  "wedding planners",
  "cafes",
  "bakeries",
  "cloud kitchens",
  "food trucks",
  "auto garages",
  "car dealers",
  "bike shops",
  "pet stores",
  "veterinary clinics",
  "daycare centres",
  "tutoring centres",
  "coding bootcamps",
  "research labs",
  "universities",
  "colleges",
  "NGO field teams",
  "CSR teams",
  "HR departments",
  "finance teams",
  "ops managers",
  "IT admins",
  "security teams",
  "legal teams",
  "procurement teams",
  "customer support teams",
  "sales teams",
  "product managers",
  "project managers",
  "QA engineers",
  "DevOps engineers",
  "data analysts",
  "BI teams",
  "content teams",
  "SEO specialists",
  "social media managers",
  "PR agencies",
  "ad agencies",
  "boutique brands",
  "D2C brands",
  "B2B vendors",
  "marketplaces",
  "dropshippers",
  "affiliate marketers",
  "influencers",
  "community managers",
  "membership sites",
  "subscription businesses",
  "co-working spaces",
  "property managers",
  "facility managers",
  "cleaning services",
  "security services",
  "home services",
  "plumbers",
  "electricians",
  "interior designers",
  "architects",
  "civil contractors",
  "landscapers",
  "farm cooperatives",
  "handicraft exporters",
  "artisans",
  "musicians",
  "bands",
  "theatre groups",
  "museums",
  "galleries",
  "tour operators",
  "homestays",
  "hostels",
  "resorts",
  "airbnb hosts",
  "fleet operators",
  "couriers",
  "last-mile delivery",
  "cold storage",
  "pharmacies",
  "medical labs",
  "diagnostic centres",
  "ayurveda clinics",
  "yoga studios",
  "wellness centres",
  "spas",
  "barber shops",
  "tailors",
  "laundry services",
  "dry cleaners",
  "stationery shops",
  "bookstores",
  "toy shops",
  "sporting goods stores",
  "outdoor gear shops",
  "furniture stores",
  "hardware stores",
  "paint shops",
  "building material suppliers",
  "steel traders",
  "scrap dealers",
  "recyclers",
  "solar installers",
  "EV charging operators",
  "telecom resellers",
  "ISP support desks",
  "cyber cafes",
  "gaming cafes",
  "esports teams",
  "board game cafes",
  "makerspaces",
  "hackerspaces",
  "incubators",
  "accelerators",
  "VC analysts",
  "angel investors",
  "family offices",
  "trusts",
  "foundations",
  "political campaigns",
  "media houses",
  "news desks",
  "fact-check teams",
  "translators",
  "interpreters",
  "voice-over artists",
  "video editors",
  "animators",
  "3D artists",
  "game developers",
  "indie hackers",
  "open-source maintainers",
  "bug bounty hunters",
  "pen testers",
  "compliance officers",
  "auditors",
  "tax consultants",
  "company secretaries",
  "chartered accountants",
  "insurance agents",
  "mutual fund distributors",
  "stock traders",
  "crypto traders",
  "NFT creators",
  "web3 startups",
  "DAO contributors",
  "no-code builders",
  "automation consultants",
  "RPA teams",
  "IoT startups",
  "robotics labs",
  "drone operators",
  "surveyors",
  "GIS teams",
  "mapping startups",
  "smart city vendors",
  "govtech vendors",
  "edtech startups",
  "healthtech startups",
  "fintech startups",
  "insurtech startups",
  "proptech startups",
  "legaltech startups",
  "regtech startups",
  "cleantech startups",
  "agritech startups",
  "foodtech startups",
  "traveltech startups",
  "sportstech startups",
  "martech startups",
  "hrtech startups",
  "recruitment firms",
  "staffing agencies",
  "gig workers",
  "delivery partners",
  "ride-share drivers",
  "taxi unions",
  "bus operators",
  "shipping lines",
  "freight forwarders",
  "customs brokers",
  "warehouse staff",
  "inventory clerks",
  "purchase managers",
  "vendor managers",
  "category managers",
  "merchandisers",
  "buyers",
  "sourcing agents",
  "quality inspectors",
  "packaging designers",
  "label printers",
  "brand managers",
  "trademark agents",
  "patent attorneys",
  "IP consultants",
  "licensing teams",
  "franchise owners",
  "franchisors",
  "multi-outlet chains",
  "QSR chains",
  "supermarket chains",
  "hyperlocal apps",
  "kirana digitization teams",
  "UPI onboarding agents",
  "payment aggregators",
  "POS resellers",
  "billing software resellers",
  "ERP implementers",
  "CRM implementers",
  "HubSpot partners",
  "Zoho partners",
  "Microsoft partners",
  "Google Workspace admins",
  "Apple business teams",
  "MDM admins",
  "school IT admins",
  "church AV teams",
  "livestream producers",
  "wedding videographers",
  "drone cinematographers",
  "real estate photographers",
  "product photographers",
  "food photographers",
  "fashion photographers",
  "model agencies",
  "casting directors",
  "talent managers",
  "record labels",
  "music producers",
  "beat makers",
  "podcast networks",
  "newsletter writers",
  "Substack authors",
  "Medium writers",
  "bloggers",
  "niche site owners",
  "comparison site owners",
  "coupon site owners",
  "deal aggregators",
  "cashback apps",
  "loyalty program managers",
  "referral program owners",
  "community-led brands",
  "Discord moderators",
  "Telegram channel admins",
  "WhatsApp group admins",
  "Facebook group admins",
  "LinkedIn creators",
  "Twitter/X creators",
  "Threads creators",
  "Pinterest pinners",
  "TikTok shops",
  "Instagram shops",
  "YouTube merch sellers",
  "Twitch streamers",
  "Kick streamers",
  "OnlyFans adjacent brands",
  "Patreon creators",
  "Gumroad sellers",
  "Teachable instructors",
  "Udemy instructors",
  "Coursera partners",
  "Skillshare teachers",
  "Khan-style educators",
  "tutoring apps",
  "homework help desks",
  "exam prep centres",
  "IELTS coaches",
  "language schools",
  "translation agencies",
  "localization teams",
  "globalization leads",
  "international sales",
  "export managers",
  "import managers",
  "customs compliance",
  "trade finance teams",
  "letter-of-credit desks",
  "forex desks",
  "treasury teams",
  "FP&A analysts",
  "CFO offices",
  "controller teams",
  "bookkeepers",
  "virtual assistants",
  "executive assistants",
  "office managers",
  "reception desks",
  "call centres",
  "BPO teams",
  "KPO teams",
  "medical transcription",
  "legal transcription",
  "court reporters",
  "stenographers",
  "paralegals",
  "law clerks",
  "mediators",
  "arbitrators",
  "notaries",
  "document scanners",
  "records management",
  "archivists",
  "digitization vendors",
  "OCR teams",
  "data entry bureaus",
  "annotation teams",
  "ML labellers",
  "AI trainers",
  "prompt engineers",
  "AI safety reviewers",
  "content moderators",
  "trust & safety teams",
  "policy teams",
  "privacy officers",
  "DPO teams",
  "GDPR consultants",
  "SOC2 auditors",
  "ISO consultants",
  "PCI consultants",
  "HIPAA consultants",
  "cyber insurance buyers",
  "MSSP clients",
  "SIEM admins",
  "SOC analysts",
  "incident response teams",
  "forensics labs",
  "red teams",
  "blue teams",
  "purple teams",
  "CISO offices",
  "CTO offices",
  "CIO offices",
  "CDO offices",
  "CMO offices",
  "COO offices",
  "CEO offices",
  "board advisors",
  "strategy consultants",
  "McKinsey-style analysts",
  "Bain-style analysts",
  "BCG-style analysts",
  "Big4 IT advisory",
  "system integrators",
  "GSIs",
  "cloud migration teams",
  "AWS architects",
  "Azure architects",
  "GCP architects",
  "Kubernetes admins",
  "Docker users",
  "serverless teams",
  "edge computing teams",
  "CDN admins",
  "DNS admins",
  "domain portfolio owners",
  "registrar resellers",
  "hosting resellers",
  "cPanel admins",
  "WordPress agencies",
  "Shopify partners",
  "WooCommerce shops",
  "Magento agencies",
  "BigCommerce merchants",
  "Square merchants",
  "Stripe integrators",
  "PayPal merchants",
  "Razorpay merchants",
  "PhonePe merchants",
  "UPI QR shops",
  "BNPL merchants",
  "subscription box brands",
  "DTC skincare",
  "DTC fashion",
  "DTC food",
  "DTC supplements",
  "DTC pet food",
  "DTC baby products",
  "DTC home decor",
  "DTC furniture",
  "DTC appliances",
  "refurbished electronics sellers",
  "second-hand marketplaces",
  "C2C sellers",
  "B2B marketplaces",
  "industrial suppliers",
  "MRO buyers",
  "procurement co-ops",
  "government tender desks",
  "PSU vendors",
  "defence suppliers",
  "aerospace suppliers",
  "automotive tier-2",
  "EV component makers",
  "battery pack assemblers",
  "inverter manufacturers",
  "solar EPC firms",
  "wind O&M teams",
  "hydro maintenance",
  "mining operators",
  "oil & gas field teams",
  "chemical plants",
  "pharma plants",
  "biotech labs",
  "clinical research orgs",
  "hospital IT",
  "EMR admins",
  "telehealth providers",
  "medical device reps",
  "diagnostic device vendors",
  "lab equipment sellers",
  "scientific instrument dealers",
  "microscope service",
  "3D printer owners",
  "CNC shop owners",
  "laser cutting shops",
  "waterjet shops",
  "sheet metal fabs",
  "welding shops",
  "plastics injection moulders",
  "packaging converters",
  "label converters",
  "flex printers",
  "signage shops",
  "LED board installers",
  "billboard agencies",
  "OOH media buyers",
  "radio stations",
  "TV stations",
  "streaming startups",
  "OTT apps",
  "smart TV app teams",
  "set-top box vendors",
  "DTH operators",
  "cable operators",
  "fiber ISPs",
  "5G enterprise buyers",
  "private 5G labs",
  "satellite internet users",
  "Starlink resellers",
  "maritime comms teams",
  "aviation MRO",
  "airport retail",
  "duty-free operators",
  "rail catering",
  "metro retail",
  "smart city IoT",
  "building automation",
  "BMS integrators",
  "HVAC contractors",
  "fire safety vendors",
  "CCTV installers",
  "access control integrators",
  "smart lock installers",
  "home automation integrators",
  "intercom installers",
  "PA system installers",
  "studio builders",
  "acoustic consultants",
  "lighting designers",
  "stage crews",
  "concert promoters",
  "festival organizers",
  "ticket platforms",
  "venue managers",
  "sports clubs",
  "stadium ops",
  "fitness franchises",
  "sports academies",
  "swimming schools",
  "martial arts dojos",
  "dance academies",
  "music schools",
  "art schools",
  "coding for kids",
  "robotics for kids",
  "STEM camps",
  "summer camps",
  "after-school programs",
  "parent cooperatives",
  "PTA groups",
  "alumni associations",
  "housing societies",
  "RWAs",
  "cooperative banks",
  "credit unions",
  "microfinance officers",
  "Self-help groups",
  "SHG federations",
  "farmer producer orgs",
  "mandi traders",
  "cold chain operators",
  "food processors",
  "dairy cooperatives",
  "poultry farms",
  "aquaculture farms",
  "greenhouse operators",
  "hydroponics startups",
  "vertical farms",
  "seed companies",
  "fertilizer dealers",
  "tractor dealers",
  "farm equipment rentals",
  "agri-drone services",
  "soil testing labs",
  "weather data users",
  "crop insurance agents",
  "warehouse receipt financiers",
  "commodity traders",
  "spice exporters",
  "tea exporters",
  "coffee roasters",
  "cocoa processors",
  "rice millers",
  "flour millers",
  "oil millers",
  "snack manufacturers",
  "beverage bottlers",
  "breweries",
  "distilleries",
  "wineries",
  "hospitality procurement",
  "ghost kitchen ops",
  "meal prep brands",
  "tiffin services",
  "catering companies",
  "banquet halls",
  "convention centres",
  "exhibition organisers",
  "trade fair booths",
  "stall fabricators",
  "promotional product vendors",
  "corporate gifting",
  "merchandise printers",
  "embroidery shops",
  "uniform suppliers",
  "PPE suppliers",
  "industrial safety vendors",
  "EHS teams",
  "OSHA compliance",
  "ISO 45001 teams",
  "sustainability teams",
  "ESG reporting",
  "carbon accounting",
  "offset marketplaces",
  "recycling startups",
  "waste management",
  "e-waste recyclers",
  "battery recyclers",
  "circular economy brands",
  "repair cafes",
  "right-to-repair advocates",
  "refurb labs",
  "ITAD vendors",
  "data destruction firms",
  "shredding services",
  "secure logistics",
  "vault storage",
  "records vaults",
  "art storage",
  "wine storage",
  "cold storage pharma",
  "vaccine cold chain",
  "blood banks",
  "organ transport",
  "ambulance dispatch",
  "emergency ops",
  "disaster response NGOs",
  "relief coordinators",
  "humanitarian logisticians",
  "UN agency vendors",
  "embassy IT staff",
  "consulate trade desks",
  "export promotion councils",
  "chamber of commerce",
  "industry associations",
  "standards bodies",
  "testing labs",
  "certification bodies",
  "inspection agencies",
  "survey ships",
  "port operators",
  "container depots",
  "customs warehouses",
  "bonded warehouses",
  "FTWZ users",
  "SEZ units",
  "EOU units",
  "STPI units",
  "startup India registrants",
  "MSME registrants",
  "Udyam holders",
  "GEM portal sellers",
  "GeM consultants",
  "tender writers",
  "bid managers",
  "proposal teams",
  "grant writers",
  "fundraising teams",
  "donor relations",
  "crowdfunding campaigns",
  "Kickstarter creators",
  "Indiegogo creators",
  "impact investors",
  "social enterprises",
  "cooperative startups",
  "worker co-ops",
  "platform co-ops",
  "union offices",
  "labour welfare boards",
  "skills councils",
  "ITI instructors",
  "polytechnic labs",
  "engineering colleges",
  "research scholars",
  "PhD labs",
  "postdoc groups",
  "journal editors",
  "peer reviewers",
  "preprint servers",
  "open access publishers",
  "library systems",
  "discovery platform users",
  "hardware reviewers",
  "tech YouTubers",
  "PC build channels",
  "laptop review sites",
  "phone review sites",
  "monitor calibrators",
  "audiophile forums",
  "mechanical keyboard communities",
  "homelab enthusiasts",
  "NAS owners",
  " Plex admins",
  "self-hosters",
  "Home Assistant users",
  "smart home tinkerers",
  "Raspberry Pi clubs",
  "Arduino clubs",
  "robotics hobbyists",
  "RC plane clubs",
  "ham radio operators",
  "citizen scientists",
  "weather station owners",
  "astronomy clubs",
  "telescope owners",
  "microscope hobbyists",
  "coin collectors",
  "stamp dealers",
  "antique dealers",
  "auction houses",
  "pawn shops",
  "gold loan NBFCs",
  "micro-lenders",
  "P2P lending",
  "crowdlending",
  "invoice discounting",
  "supply chain finance",
  "vendor financing",
  "working capital lenders",
  "merchant cash advance",
  "POS lending",
  "embedded finance teams",
  "banking-as-a-service",
  "neobank partners",
  "wallet apps",
  "super-app teams",
  "ride-hail product",
  "food delivery product",
  "grocery quick commerce",
  "10-minute delivery ops",
  "dark store managers",
  "picker teams",
  "last-touch QA",
  "returns processing",
  "reverse logistics",
  "refurbishment centres",
  "marketplace trust teams",
  "seller onboarding",
  "KYC ops",
  "AML analysts",
  "fraud ops",
  "chargeback teams",
  "dispute resolution",
  "customer success",
  "onboarding specialists",
  "implementation consultants",
  "customer education",
  "developer relations",
  "developer advocates",
  "API product managers",
  "platform engineers",
  "marketplace PMs",
  "growth hackers",
  "performance marketers",
  "paid search teams",
  "SEO agencies",
  "link builders",
  "content farms",
  "programmatic SEO teams",
  "Ebenezer readers",
];

export const HARDWARE_BRANDS = [
  "Dell", "HP", "Lenovo", "Asus", "Acer", "Apple", "MSI", "Samsung", "LG", "Sony",
  "Intel", "AMD", "NVIDIA", "Qualcomm", "MediaTek", "Apple Silicon", "ARM", "Raspberry Pi",
  "Logitech", "Razer", "Corsair", "HyperX", "SteelSeries", "Keychron", "Redragon",
  "TP-Link", "Netgear", "D-Link", "Ubiquiti", "ASUS ROG", "BenQ", "ViewSonic", "AOC",
  "Crucial", "Kingston", "Samsung Storage", "WD", "Seagate", "SanDisk", "Lexar",
  "Cooler Master", "NZXT", "Thermaltake", "Antec", "EVGA", "Gigabyte", "ASRock",
  "OnePlus", "Xiaomi", "Realme", "Oppo", "Vivo", "Motorola", "Nokia", "Google Pixel",
  "Canon", "Nikon", "Fujifilm", "GoPro", "DJI", "Blue Yeti", "Audio-Technica", "Shure",
];

export const HARDWARE_SCENARIOS = [
  "office work", "gaming", "video editing", "programming", "student use", "travel",
  "home lab", "NAS storage", "4K editing", "streaming", "music production", "CAD work",
  "3D rendering", "AI training", "machine learning", "data science", "virtual machines",
  "dual monitor setup", "ultrawide gaming", "budget build", "silent PC", "compact SFF",
  "rack mount", "workstation upgrade", "RAM upgrade path", "SSD migration", "GPU upgrade",
  "Wi-Fi 6 home", "mesh Wi-Fi", "gigabit switching", "POE cameras", "smart home hub",
  "phone photography", "mobile gaming", "battery life focus", "repair and spare parts",
  "refurbished value", "warranty comparison", "India pricing", "global pricing",
  "monsoon humidity", "dusty environments", "power backup", "UPS sizing", "surge protection",
  "cable management", "ergonomic desk", "standing desk", "mechanical keyboard typing",
  "wireless mouse latency", "webcam quality", "headset mic clarity", "noise cancelling",
  "studio monitors", "USB-C docking", "Thunderbolt dock", "multi-device charging",
  "laptop cooling pad", "thermal paste", "fan curve tuning", "BIOS update safety",
  "driver updates", "firmware risks", "EOL support", "recycle old hardware", "trade-in value",
  "enterprise fleet", "school lab", "cyber cafe", "POS terminal", "kiosk mode",
  "industrial PC", "fanless PC", "mini PC HTPC", "home theatre", "projector pairing",
  "console streaming", "Steam Deck-like", "handheld gaming", "VR readiness", "Ray tracing",
  "144Hz gaming", "240Hz esports", "color accurate display", "HDR content", "OLED burn-in",
  "IPS vs VA", "TN legacy", "touchscreen laptops", "2-in-1 convertibles", "Chromebook limits",
  "Linux compatibility", "Hackintosh risks", "Windows 11 TPM", "Secure Boot", "BitLocker",
  "TPM modules", "smart card readers", "fingerprint sensors", "facial recognition",
  "privacy shutter", "kill switch mic", "hardware encryption", "self-encrypting drives",
  "RAID home NAS", "ZFS basics", "backup strategy", "cloud sync vs local", "offline archive",
  "photo backup", "video archive", "music library", "ebook reader", "tablet drawing",
  "stylus latency", "e-ink tablets", "kindle alternatives", "kids tablet", "parental controls",
  "router parental controls", "guest Wi-Fi", "VLAN home", "Pi-hole DNS", "ad blocking network",
  "VPN router", "travel router", "4G failover", "5G FWA", "satellite backup link",
  "rural connectivity", "urban apartment Wi-Fi", "concrete wall penetration", "multi-floor home",
  "shop billing PC", "warehouse scanner", "barcode printer", "label printer thermal",
  "receipt printer", "cash drawer PC", "dual display POS", "kitchen display", "menu board PC",
  "security NVR", "door access PC", "time attendance", "biometric attendance", "CCTV storage sizing",
];

export const STUDIO_TOPICS = [
  "implementation guide",
  "cost planning",
  "timeline expectations",
  "team readiness",
  "vendor selection",
  "security checklist",
  "SEO impact",
  "maintenance plan",
  "migration path",
  "ROI measurement",
  "common mistakes",
  "success metrics",
];

export const STORE_TOPICS = [
  "setup walkthrough",
  "who should buy",
  "comparison tips",
  "integration ideas",
  "print and delivery",
  "license explained",
  "support expectations",
  "upgrade path",
];

type MatrixDims = number[];

function dimsFor(channel: ContentChannel): MatrixDims {
  switch (channel) {
    case "tools":
      return [Math.max(TOOLS.length, 1), EXPLAINER_ANGLES.length, AUDIENCES.length];
    case "studio":
      return [
        Math.max(SERVICE_LANDINGS.length, 1),
        EXPLAINER_ANGLES.length,
        AUDIENCES.length,
        STUDIO_TOPICS.length,
      ];
    case "store":
      return [
        Math.max(STORE_PRODUCTS.filter((p) => p.status === "published").length, 1),
        EXPLAINER_ANGLES.length,
        AUDIENCES.length,
        STORE_TOPICS.length,
      ];
    case "discover":
      return [
        Math.max(CATALOG_CATEGORIES.length, 1),
        HARDWARE_BRANDS.length,
        EXPLAINER_ANGLES.length,
        HARDWARE_SCENARIOS.length,
      ];
  }
}

export function channelMatrixProduct(channel: ContentChannel): number {
  return dimsFor(channel).reduce((a, b) => a * b, 1);
}

export function channelArticleCount(channel: ContentChannel): number {
  return Math.min(CHANNEL_ARTICLE_TARGET, channelMatrixProduct(channel));
}

export function indexToCoords(channel: ContentChannel, index: number): number[] {
  const dims = dimsFor(channel);
  const coords: number[] = [];
  let n = index % channelMatrixProduct(channel);
  for (let i = dims.length - 1; i >= 0; i--) {
    coords.unshift(n % dims[i]);
    n = Math.floor(n / dims[i]);
  }
  return coords;
}

export function coordsToIndex(channel: ContentChannel, coords: number[]): number {
  const dims = dimsFor(channel);
  let index = 0;
  for (let i = 0; i < dims.length; i++) {
    index = index * dims[i] + (coords[i] ?? 0);
  }
  return index;
}
