/**
 * Curated AI / SaaS discovery entries.
 * Logos: Clearbit brand marks or official CDN — never Unsplash.
 * Pricing: only published public tiers, or "Check official site".
 */

import type { Tool } from "./types";

export type { Tool } from "./types";

const UPDATED = "2026-08-20T10:00:00.000Z";

export const DISCOVERY_TOOLS: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "General-purpose AI assistant for writing, coding help, and research.",
    description:
      "OpenAI's ChatGPT is a widely used conversational AI for drafting, summarizing, brainstorming, and light coding help. Free and paid tiers exist; exact limits change — verify on the official site.",
    category: "AI Writing",
    logo: "🤖",
    domain: "openai.com",
    url: "https://chatgpt.com/",
    pricing: {
      free: true,
      freeLabel: "Free plan available (limits apply)",
      paid: "Check official site",
      paidLabel: "Plus / Team / Enterprise — verify current pricing",
    },
    rating: 5,
    bestFor: "Writers, students, marketers, and general knowledge work",
    whoShouldAvoid: "Teams that need guaranteed private on-prem models or strict offline use",
    pros: ["Strong general writing and reasoning", "Large ecosystem of custom GPTs", "Wide public documentation"],
    cons: ["Paid features and limits change over time", "Not a specialist video/image studio"],
    features: ["Chat + file uploads (plan dependent)", "Custom GPTs", "Web browsing on some plans"],
    platforms: ["Web", "iOS", "Android"],
    lastUpdated: UPDATED,
    badge: "Most Popular",
    highlighted: true,
  },
  {
    id: "claude",
    name: "Claude",
    tagline: "Long-context AI for careful writing, analysis, and coding assistance.",
    description:
      "Anthropic's Claude focuses on helpful, careful answers and long documents. Strong for research notes, rewriting, and developer Q&A. Confirm current plan limits on Anthropic's site.",
    category: "AI Research",
    logo: "🟠",
    domain: "anthropic.com",
    url: "https://claude.ai/",
    pricing: {
      free: true,
      freeLabel: "Free plan available (limits apply)",
      paid: "Check official site",
      paidLabel: "Pro / Team — verify current pricing",
    },
    rating: 5,
    bestFor: "Researchers, analysts, and teams working with long documents",
    whoShouldAvoid: "Users who only need a tiny free chat quota and nothing else",
    pros: ["Strong long-document handling", "Careful, structured answers", "Useful for coding explanations"],
    cons: ["Feature set varies by plan", "Image/video generation is not the core focus"],
    features: ["Long context chats", "Projects / artifacts (plan dependent)", "API available separately"],
    platforms: ["Web", "Desktop (where offered)"],
    lastUpdated: UPDATED,
    badge: "Editor's Pick",
    highlighted: true,
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Google's multimodal AI assistant tied into the Google ecosystem.",
    description:
      "Gemini helps with writing, research, and multimodal prompts inside Google's product family. Plan availability differs by region — check Google's official pages for India access and pricing.",
    category: "AI Productivity",
    logo: "✨",
    domain: "gemini.google.com",
    url: "https://gemini.google.com/",
    pricing: {
      free: true,
      freeLabel: "Free access available in supported regions",
      paid: "Check official site",
      paidLabel: "Google AI Premium / Workspace add-ons — verify",
    },
    rating: 4,
    bestFor: "People already in Gmail, Docs, and Google Workspace",
    whoShouldAvoid: "Users who need a non-Google vendor for compliance reasons",
    pros: ["Tight Google product integration", "Multimodal prompts", "Strong search-adjacent research use"],
    cons: ["Availability and plans vary by country", "Enterprise controls live in Workspace tiers"],
    features: ["Chat", "Multimodal prompts", "Workspace integrations (plan dependent)"],
    platforms: ["Web", "Android", "iOS"],
    lastUpdated: UPDATED,
    highlighted: true,
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI pair programmer inside your editor.",
    description:
      "GitHub Copilot suggests code as you type in VS Code, JetBrains, and other editors. Pricing is published by GitHub; always confirm Individual vs Business plans before buying.",
    category: "AI Coding",
    logo: "💻",
    domain: "github.com",
    url: "https://github.com/features/copilot",
    pricing: {
      free: false,
      paid: "Check official site",
      paidLabel: "Individual / Business / Enterprise — verify GitHub pricing",
    },
    rating: 5,
    bestFor: "Developers who want inline code suggestions daily",
    whoShouldAvoid: "Teams with strict bans on cloud AI code assistants",
    pros: ["Works inside popular IDEs", "Speeds boilerplate and tests", "GitHub ecosystem fit"],
    cons: ["Paid for most commercial use", "Suggestions still need human review"],
    features: ["Inline completions", "Chat in editor (plan dependent)", "PR summaries (plan dependent)"],
    platforms: ["VS Code", "JetBrains", "Neovim", "Visual Studio"],
    lastUpdated: UPDATED,
    badge: "Editor's Pick",
    highlighted: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    tagline: "AI-first code editor built for agentic coding workflows.",
    description:
      "Cursor is a VS Code–style editor with deep AI editing, chat, and codebase awareness. Confirm current free trial and Pro pricing on cursor.com.",
    category: "AI Coding",
    logo: "⌨️",
    domain: "cursor.com",
    url: "https://cursor.com/",
    pricing: {
      free: true,
      freeLabel: "Hobby / free tier may be available — verify",
      paid: "Check official site",
      paidLabel: "Pro and team plans — verify current pricing",
    },
    rating: 5,
    bestFor: "Developers building features quickly with AI agents in the editor",
    whoShouldAvoid: "People who only want a thin plugin inside an existing IDE",
    pros: ["Editor + AI tightly integrated", "Strong multi-file edits", "Popular with modern web teams"],
    cons: ["Pricing and model access change frequently", "Requires internet for AI features"],
    features: ["AI chat", "Inline edit", "Codebase indexing"],
    platforms: ["macOS", "Windows", "Linux"],
    lastUpdated: UPDATED,
    badge: "Most Popular",
    highlighted: true,
  },
  {
    id: "midjourney",
    name: "Midjourney",
    tagline: "High-quality AI image generation for creative work.",
    description:
      "Midjourney generates images from text prompts, popular with designers and marketers. Access and billing are managed on Midjourney's official site — do not assume old Discord-only pricing.",
    category: "AI Image",
    logo: "🖼️",
    domain: "midjourney.com",
    url: "https://www.midjourney.com/",
    pricing: {
      free: false,
      paid: "Check official site",
      paidLabel: "Subscription plans — verify current tiers",
    },
    rating: 5,
    bestFor: "Concept art, moodboards, and marketing visuals",
    whoShouldAvoid: "Users who need free unlimited commercial generation",
    pros: ["Strong aesthetic quality", "Active creative community", "Good for exploration"],
    cons: ["Paid access required for serious use", "Not a full design suite like Canva"],
    features: ["Text-to-image", "Variations", "Upscaling (plan dependent)"],
    platforms: ["Web"],
    lastUpdated: UPDATED,
  },
  {
    id: "runway",
    name: "Runway",
    tagline: "AI video generation and creative toolkit for short clips.",
    description:
      "Runway offers AI video tools used for shorts, effects, and creative prototyping. Credit-based pricing changes — always check runwayml.com for current plans before budgeting.",
    category: "AI Video",
    logo: "🎬",
    domain: "runwayml.com",
    url: "https://runwayml.com/",
    pricing: {
      free: true,
      freeLabel: "Limited free credits may be available — verify",
      paid: "Check official site",
      paidLabel: "Credit / subscription plans — verify",
    },
    rating: 4,
    bestFor: "Creators prototyping AI video for YouTube Shorts and social",
    whoShouldAvoid: "Teams needing guaranteed long-form 4K production pipelines only",
    pros: ["Purpose-built for AI video", "Regular model updates", "Creator-friendly workflow"],
    cons: ["Credits can burn quickly", "Output quality varies by prompt and model"],
    features: ["Text/image to video", "Editing tools", "Generative effects"],
    platforms: ["Web"],
    lastUpdated: UPDATED,
    badge: "Best Value",
  },
  {
    id: "hubspot",
    name: "HubSpot CRM",
    tagline: "CRM and marketing hub popular with growing sales teams.",
    description:
      "HubSpot's free CRM covers contacts, deals, and pipelines. Paid Marketing/Sales Hubs unlock automation. Confirm India pricing on HubSpot's site.",
    category: "CRM",
    logo: "🧡",
    domain: "hubspot.com",
    url: "https://www.hubspot.com/products/crm",
    pricing: {
      free: true,
      freeLabel: "Free CRM available",
      paid: "Check official site",
      paidLabel: "Starter / Professional / Enterprise — verify",
    },
    rating: 5,
    bestFor: "Small businesses starting CRM + light marketing automation",
    whoShouldAvoid: "Shops that only need simple invoicing with no pipeline",
    pros: ["Generous free CRM", "Wide education content", "Integrations ecosystem"],
    cons: ["Paid hubs become expensive at scale", "Can feel heavy for tiny teams"],
    features: ["Contacts & deals", "Email tracking (plan dependent)", "Reporting"],
    platforms: ["Web", "iOS", "Android"],
    lastUpdated: UPDATED,
    badge: "Most Popular",
    highlighted: true,
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    tagline: "Affordable CRM that pairs well with Zoho Invoice and Books.",
    description:
      "Zoho CRM is strong for Indian SMBs already in the Zoho suite. Free and paid editions exist — verify seat limits on Zoho's pricing page.",
    category: "CRM",
    logo: "🔵",
    domain: "zoho.com",
    logoImg: "https://www.zohowebstatic.com/sites/zweb/images/zoho_general_pages/zoho-logo-web.svg",
    url: "https://www.zoho.com/crm/",
    affiliateNote: "Zoho affiliate program — use approved Impact/Zoho tracking links",
    pricing: {
      free: true,
      freeLabel: "Free edition available (limits apply)",
      paid: "Check official site",
      paidLabel: "Standard / Professional / Enterprise — verify",
    },
    rating: 4,
    bestFor: "Indian SMBs wanting CRM + Zoho apps under one vendor",
    whoShouldAvoid: "Teams standardized on Salesforce/HubSpot already",
    pros: ["India-friendly pricing narrative", "Zoho ecosystem", "Customization options"],
    cons: ["UI can feel dense", "Advanced automation on higher plans"],
    features: ["Leads & deals", "Workflow rules", "Zoho suite integrations"],
    platforms: ["Web", "Mobile"],
    lastUpdated: UPDATED,
    badge: "Best for India",
  },
  {
    id: "asana",
    name: "Asana",
    tagline: "Project management for teams tracking tasks and timelines.",
    description:
      "Asana organizes work across boards, lists, and timelines. Free plan exists for small teams; Business features are paid — confirm on asana.com.",
    category: "Project Management",
    logo: "🔴",
    domain: "asana.com",
    url: "https://asana.com/",
    pricing: {
      free: true,
      freeLabel: "Free for small teams (limits apply)",
      paid: "Check official site",
      paidLabel: "Premium / Business — verify",
    },
    rating: 4,
    bestFor: "Marketing and ops teams coordinating multi-step projects",
    whoShouldAvoid: "Solo freelancers who only need a simple personal to-do list",
    pros: ["Clear task ownership", "Timeline views on paid plans", "Integrations"],
    cons: ["Advanced views locked to paid tiers", "Can be noisy for tiny teams"],
    features: ["Tasks & projects", "Workload (plan dependent)", "Rules / automation"],
    platforms: ["Web", "iOS", "Android"],
    lastUpdated: UPDATED,
  },
  {
    id: "figma",
    name: "Figma",
    tagline: "Collaborative UI/UX design and prototyping in the browser.",
    description:
      "Figma is the standard for product UI design and handoff. Free starter seats exist; Organization plans are paid — verify on figma.com.",
    category: "UI/UX",
    logo: "🟣",
    domain: "figma.com",
    url: "https://www.figma.com/",
    pricing: {
      free: true,
      freeLabel: "Free starter available (limits apply)",
      paid: "Check official site",
      paidLabel: "Professional / Organization — verify",
    },
    rating: 5,
    bestFor: "Designers and product teams collaborating on interfaces",
    whoShouldAvoid: "Print-only designers who never need interactive prototypes",
    pros: ["Real-time collaboration", "Dev Mode handoff", "Huge community files"],
    cons: ["Advanced team controls on higher plans", "Offline is limited"],
    features: ["Design files", "Prototyping", "FigJam (separate/bundled plans)"],
    platforms: ["Web", "Desktop apps"],
    lastUpdated: UPDATED,
    badge: "Editor's Pick",
    highlighted: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    tagline: "Hosting and deployment platform popular for Next.js apps.",
    description:
      "Vercel deploys frontend and full-stack apps with previews and edge networking. Hobby is free for personal projects; Pro is paid — check vercel.com/pricing.",
    category: "Hosting",
    logo: "▲",
    domain: "vercel.com",
    url: "https://vercel.com/",
    pricing: {
      free: true,
      freeLabel: "Hobby free tier for personal projects",
      paid: "Check official site",
      paidLabel: "Pro / Enterprise — verify",
    },
    rating: 5,
    bestFor: "Developers shipping Next.js and modern frontends",
    whoShouldAvoid: "Teams needing only cheap shared PHP hosting",
    pros: ["Excellent Next.js DX", "Preview deployments", "Edge network"],
    cons: ["Costs scale with team and bandwidth", "Not a general VPS replacement"],
    features: ["Git deployments", "Preview URLs", "Serverless / edge functions"],
    platforms: ["Web"],
    lastUpdated: UPDATED,
  },
  {
    id: "supabase",
    name: "Supabase",
    tagline: "Postgres database, auth, and APIs as a managed backend.",
    description:
      "Supabase provides Postgres, auth, storage, and realtime APIs. Free tier exists with limits; Pro is paid — verify on supabase.com/pricing.",
    category: "Databases",
    logo: "🟢",
    domain: "supabase.com",
    url: "https://supabase.com/",
    pricing: {
      free: true,
      freeLabel: "Free tier with project limits",
      paid: "Check official site",
      paidLabel: "Pro / Team — verify",
    },
    rating: 5,
    bestFor: "Builders who want Postgres + auth without managing servers",
    whoShouldAvoid: "Enterprises locked into a different cloud database standard",
    pros: ["Real Postgres", "Auth + storage included", "Strong docs"],
    cons: ["Free limits for production scale", "You still design schema carefully"],
    features: ["Postgres", "Auth", "Storage", "Edge functions"],
    platforms: ["Web", "Client SDKs"],
    lastUpdated: UPDATED,
    badge: "Best Value",
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    tagline: "SEO research platform for keywords, backlinks, and content gaps.",
    description:
      "Ahrefs is a professional SEO suite. Plans are paid with different crawl/credit limits — always confirm current pricing on ahrefs.com before recommending a budget.",
    category: "SEO",
    logo: "🟠",
    domain: "ahrefs.com",
    url: "https://ahrefs.com/",
    pricing: {
      free: false,
      paid: "Check official site",
      paidLabel: "Lite and higher plans — verify",
    },
    rating: 5,
    bestFor: "SEO specialists and content teams doing competitive research",
    whoShouldAvoid: "Absolute beginners who only need a free keyword suggestion box",
    pros: ["Strong backlink index", "Content explorer", "Site audit tools"],
    cons: ["Expensive for tiny sites", "Steep for casual bloggers"],
    features: ["Keywords", "Site Explorer", "Site Audit"],
    platforms: ["Web"],
    lastUpdated: UPDATED,
  },
];
